# Generated by Django 5.2.3 on 2025-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deu', models.CharField(max_length=2048)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('bed', models.CharField(blank=True, max_length=2048, null=True)),
                ('art', models.IntegerField(blank=True, null=True)),
                ('dif', models.IntegerField(blank=True, null=True)),
                ('typ', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
