# Generated by Django 5.2.3 on 2025-07-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btwo',
            name='qnu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
