from menu.models import Btwo

german_words = [
    "der Betrieb, -e",
    "ausreichend",
    "selbstständig",
    "sich beschweren, beschwert sich, beschwerte sich, hat sich beschwert",
    "der Unfall, ¨-e",
    "→ D, A: Fasching; CH: Fasnacht",
    "das Hotel, -s",
    "aufräumen, räumt auf, räumte auf, hat aufgeräumt",
    "die Bankleitzahl, -en",
    "der Unternehmer, -",
    "passiv",
    "chic/schick",
    "der Sturm, ¨-e",
    "stehen bleiben",
    "das Spiel, -e",
    "aufwachen, wacht auf, wachte auf, ist aufgewacht",
    "→ D, A: Urlaub",
    "hier/hier-",
    "der Notruf",
    "der Beruf, -e",
    "wütend",
    "ebenso",
    "Goethe Zertifikat B1 Wortliste",
    "kommen, kommt, kam, ist gekommen",
    "schaffen, schafft, schaffte, hat geschafft",
    "das Quartier, -e (CH)",
    "die Sicherheit, -en",
    "kaum",
    "knapp",
    "die Lernerin, -nen",
    "die Garage, -n",
    "und",
    "das Instrument, -e",
    "der Spezialist, -en",
    "abschreiben, schreibt ab, schrieb ab, hat abgeschrieben",
    "das Kraftwerk, -e",
    "die Präsentation, -en",
    "in Pension gehen/sein (D, A)",
    "die Postleitzahl, -en",
    "nein",
    "der Essig",
    "sorgen, sorgt, sorgte, hat gesorgt",
    "die Aussprache",
    "der Plan, ¨-e",
    "raus/raus-",
    "zugehen, geht zu, ging zu, ist zugegangen",
    "sich verhalten, verhält sich, verhielt sich, hat sich verhalten",
    "die Kommunikation",
    "schnell",
    "jedes Mal",
    "erklären, erklärt, erklärte, hat erklärt",
    "der Nachwuchs",
    "die Geschwindigkeit, -en",
    "wild",
    "der Film, -e",
    "grüßen, grüßt, grüßte, hat gegrüßt",
    "die Bibliothek, -en",
    "wissen, weiß, wusste, hat gewusst",
    "die Übersetzung, -en",
    "die Lebensmittel (Pl.)",
    "die Klasse, -n",
    "→ A: Semmel; CH: Brötli",
    "das Denkmal, ¨-er",
    "markieren, markiert, markierte, hat markiert",
    "die Reservierung, -en",
    "die Gitarre, -n",
    "die Hausfrau",
    "die Übersetzerin, -nen",
    "modern",
    "windig",
    "der Turm, ¨-e",
    "ein-",
    "→ Brieftasche; A: Geldbörse",
    "die Serviceangestellte, -n (CH)",
    "aufschreiben",
    "(sich) vorbereiten, bereitet vor, bereitete vor, hat vorbereitet",
    "unten",
    "der Held, -en",
    "der Karneval, -s/-e (D)",
    "heizen, heizt, heizte, hat geheizt",
    "überfahren, überfährt, überfuhr, hat überfahren",
    "das Kissen, -",
    "die Wäsche",
    "unglaublich",
    "die Absicht, -en",
    "dafür",
    "→ D, A: parken",
    "speichern, speichert, speicherte, hat gespeichert",
    "befriedigend",
    "beliebt",
    "das Gewitter, -",
    "der Spaziergang, ¨-e",
    "der Junge, -n (D)",
    "→ Gang; D: Flur",
    "der Spaß",
    "der Monitor, -e",
    "abfahren, fährt ab, fuhr ab, ist abgefahren",
    "der Flur, -e",
    "die Kerze, -n",
    "das Haustier, -e",
    "mit",
    "gar",
    "die Radfahrerin, -nen",
    "Abgase (Pl.)",
    "→ D, A: Knödel",
    "der Hut, ¨-e",
    "die Änderung, -en",
    "dabei",
    "der Kunststoff, -e",
    "das Talent, -e",
    "wiederholen, wiederholt, wiederholte, hat wiederholt",
    "der Virus, Viren",
    "das Mittel, -",
    "ernsthaft",
    "erhöhen, erhöht, erhöhte, hat erhöht",
    "reinigen, reinigt, reinigte, hat gereinigt",
    "aus",
    "schade",
    "die Leitung, -en",
    "reduzieren, reduziert, reduzierte, hat reduziert",
    "das Fett",
    "die Vorstellung, -en",
    "→ A: Erdapfel",
    "die Wirtin, -nen",
    "der Umweltschutz",
    "das Interesse, -n",
    "der Hügel, -",
    "virtuell",
    "pflanzen, pflanzt, pflanzte, hat gepflanzt",
    "erziehen, erzieht, erzog, hat erzogen",
    "abholen, holt ab, holte ab, hat abgeholt",
    "der Alltag",
    "nett",
    "das Gewürz, -e",
    "zwar",
    "dankbar",
    "mal",
    "sinken, sinkt, sank, ist gesunken",
    "schädlich",
    "sparsam",
    "die Sportart, -en",
    "→ D, CH: (Back-)Ofen",
    "die Anwältin, -nen",
    "kosten, kostet, kostete, hat gekostet (A)",
    "→ D, CH: Büchse",
    "(sich etwas) aussuchen, sucht aus, suchte aus, hat ausgesucht",
    "enttäuschen, enttäuscht, enttäuschte, hat enttäuscht",
    "das Telefon, -e",
    "als ob",
    "der Nebel, -",
    "gesund",
    "wert",
    "der Unterschied, -e",
    "die Malerin, -nen",
    "das Paar, -e",
    "die Feuerwehr, -en",
    "backen, bäckt/backt, backte, hat gebacken",
    "→ D, A: Bahnsteig",
    "der Reifen, -",
    "Volleyball",
    "festhalten, hält fest, hielt fest, hat festgehalten",
    "das Handy, -s",
    "die Breite, -n",
    "der Wunsch, ¨-e",
    "der Test, -s",
    "der Briefumschlag, ¨-e",
    "die Messe, -n",
    "ausgeben, gibt aus, gab aus, hat ausgegeben",
    "der Kuli, -s",
    "der Trainer, -",
    "in Rente gehen/sein (D)",
    "diskutieren, diskutiert, diskutierte, hat diskutiert",
    "der Nerv, -en",
    "die Post",
    "erfinden, erfindet, erfand, hat erfunden",
    "die Ursache, -n",
    "die Autobahn, -en",
    "selbstverständlich",
    "ziemlich",
    "retten, rettet, rettete, hat gerettet",
    "gefährlich",
    "die Freiheit",
    "die Geburt, -en",
    "der Lautsprecher, -",
    "sich verlaufen, verläuft sich, verlief sich, hat sich verlaufen",
    "der Verlust, -e",
    "sogar",
    "alt",
    "das Schnitzel, -",
    "brauchen, braucht, brauchte, hat gebraucht",
    "die Produktion",
    "flexibel",
    "das Material",
    "die Dame, -n",
    "einheitlich",
    "die Nord-/Ostsee",
    "die Migrantin, -nen",
    "besorgen, besorgt, besorgte, hat besorgt",
    "versprechen, verspricht, versprach, hat versprochen",
    "der Typ, -en",
    "die Anzeige, -n",
    "der Flughafen, ¨-",
    "transportieren, transportiert, transportierte, hat transportiert",
    "merken, merkt, merkte, hat gemerkt",
    "feststellen, stellt fest, stellte fest, hat festgestellt",
    "wenden, wendet, wendete, hat gewendet",
    "die Vermittlung, -en",
    "die Tür, -en",
    "der Zug, ¨-e",
    "anders (((1qq)))",
    "auswählen, wählt aus, wählte aus, hat ausgewählt",
    "interessieren, interessiert, interessierte, hat interessiert",
    "zelten, zeltet, zeltete, hat gezeltet",
    "der Pensionist, -en",
    "der Schrank, ¨-e (D, CH)",
    "die Zeit",
    "die Haltestelle, -n",
    "die Aussicht, -en",
    "das Konsulat, -e",
    "der Wetterbericht, -e",
    "die Einfahrt, -en",
    "die Zinsen (nur Pl.)",
    "der Löffel, -",
    "überreden, überredet, überredete, hat überredet",
    "die Landung, -en",
    "der Wind, -e",
    "die Ampel, -n",
    "→ D: Kasten",
    "spüren, spürt, spürte, hat gespürt",
    "die Profisportlerin, -nen",
    "leiden, leidet, litt, hat gelitten",
    "nichts",
    "ordentlich",
    "viel/viele",
    "das Referat, -e",
    "der Schirm, -e",
    "das Tuch, ¨-er",
    "typisch",
    "das Teil, -e",
    "die Richtung, -en",
    "die Künstlerin, -nen",
    "mehr (siehe auch viel)",
    "breit",
    "der Mond, -e",
    "die Rundfahrt, -en",
    "einkaufen, kauft ein, kaufte ein, hat eingekauft",
    "zu sein, ist zu, war zu, ist zu gewesen",
    "entscheiden, entscheidet, entschied, hat entschieden",
    "das Regal, -e",
    "sich lohnen, lohnt sich, lohnte sich, hat sich gelohnt",
    "die Küche, -n",
    "stürzen, stürzt, stürzte, ist gestürzt",
    "basteln, bastelt, bastelte, hat gebastelt",
    "kalt",
    "der Topf, ¨-e (D, A)",
    "verzeihen, verzeiht, verzieh, hat verziehen",
    "die Migration",
    "→ CH: Ferien",
    "tragen, trägt, trug, hat getragen",
    "schuldig",
    "übersetzen, übersetzt, übersetzte, hat übersetzt",
    "schenken, schenkt, schenkte, hat geschenkt",
    "zukünftig",
    "gratulieren, gratuliert, gratulierte, hat gratuliert",
    "der Kugelschreiber, -",
    "→ Personenstand; D, A: Familienstand",
    "kleben, klebt, klebte, hat geklebt",
    "die Birne, -n",
    "der Pullover, -",
    "bio(logisch)",
    "das Girokonto, -en",
    "neugierig",
    "trocknen, trocknet, trocknete, hat/ist getrocknet",
    "die Torte, -n",
    "der Ski/Schi, -er/-",
    "stellen, stellt, stellte, hat gestellt",
    "genug",
    "indem",
    "genauso",
    "klicken, klickt, klickte, hat geklickt",
    "ausziehen, zieht aus, zog aus, hat/ist ausgezogen",
    "krank",
    "zahlreich",
    "das Buffet, -s",
    "der Beamte, -n",
    "international",
    "umsonst",
    "beantworten, beantwortet, beantwortete, hat beantwortet",
    "reparieren, repariert, reparierte, hat repariert",
    "die Sendung, -en",
    "die Fleischhauerin, -nen (A)",
    "→ A: Ordination",
    "das Datum, die Daten",
    "das Ende",
    "ja",
    "die Aktion, -en",
    "die Dose, -n",
    "umarmen, umarmt, umarmte, hat umarmt",
    "→ D, A: Hausmeister",
    "zuschauen",
    "die Kreuzung, -en",
    "sozial",
    "kennenlernen, lernt kennen, lernte kennen, hat kennengelernt",
    "sonst",
    "die Mechanikerin, -nen",
    "interessiert",
    "der Automat, -en",
    "das Brötchen, - (D)",
    "blühen, blüht, blühte, hat geblüht",
    "die Quittung, -en",
    "getrennt leben",
    "kurz",
    "die Senioren (Pl.)",
    "buchstabieren, buchstabiert, buchstabierte, hat buchstabiert",
    "kaputtmachen",
    "der Einbrecher, -",
    "→ A: Ordination",
    "über",
    "etwas",
    "mutig",
    "fehlen, fehlt, fehlte, hat gefehlt",
    "die Führung, -en",
    "die Verbrecherin, -nen",
    "verbrauchen, verbraucht, verbrauchte, hat verbraucht",
    "(sich) fürchten, fürchtet, fürchtete, hat gefürchtet",
    "feiern, feiert, feierte, hat gefeiert",
    "die Energie, -n",
    "können, kann, konnte, hat gekonnt (hat können als Modalverb)",
    "unter",
    "der Bekannte, -n",
    "der Mann, ¨-er",
    "darstellen, stellt dar, stellte dar, hat dargestellt",
    "der Raum, ¨-e",
    "manch-",
    "die Mobilbox, -en",
    "der Zweifel, -",
    "die Arbeitslosigkeit",
    "der Hunger",
    "eintragen, trägt ein, trug ein, hat eingetragen",
    "jemals",
    "der Abschied, -e",
    "beobachten, beobachtet, beobachtete, hat beobachtet",
    "aussprechen, spricht aus, sprach aus, hat ausgesprochen",
    "der Zucker",
    "die Temperatur, -en",
    "die Fasnacht (CH)",
    "erst",
    "das Gedicht, -e",
    "die Versicherung, -en",
    "der Spiegel, -",
    "glücklich",
    "der Service",
    "die Kurve, -n",
    "das Dach, ¨-er",
    "gerade",
    "verheiratet",
    "das Sofa, -s",
    "der Kalender, -",
    "lieb",
    "daneben",
    "die Einnahme, -n",
    "leer",
    "die Nachbarin, nen",
    "gespannt",
    "der Antrag, ¨-e",
    "die Brieftasche, -n",
    "außer",
    "der Anbieter, -",
    "das Leben",
    "der Verwandte, -n",
    "das Gefühl, -e",
    "die Überraschung,-en",
    "kündigen, kündigt, kündigte, hat gekündigt",
    "fast",
    "der Tee",
    "die Hand, ¨-e",
    "losfahren, fährt los, fuhr los, ist losgefahren",
    "möglichst",
    "die Zuschauerin, -nen",
    "Früchte (CH)",
    "der Hörer, -;",
    "baden, badet, badete, hat gebadet",
    "der Apparat, -e",
    "die See",
    "→ D: Brötchen; CH: Brötli",
    "daher",
    "bedeuten, bedeutet, bedeutete, hat bedeutet",
    "untersuchen, untersucht, untersuchte, hat untersucht",
    "das Stiegenhaus, ¨-er (A)",
    "die Krise, -n",
    "die Stelle, -n",
    "die Adresse, -n",
    "seltsam",
    "die Erziehung",
    "der Anschluss, ¨-e",
    "das Stück/-stück, -e",
    "der Abfalleimer, -",
    "die Ausstellung, -en",
    "die Apotheke, -n",
    "die Auswahl, -en",
    "der Durst",
    "(herunter-)fahren, fährt herunter, fuhr herunter, hat heruntergefahren",
    "klettern, klettert, kletterte, ist geklettert",
    "der Schinken, -",
    "der Empfang, ¨-e",
    "abmachen, macht ab, machte ab, hat abgemacht",
    "die Kartoffel, -n",
    "der Tierpark, -s",
    "die Patientin, -nen",
    "senkrecht",
    "die Droge, -n",
    "der Leiter, -",
    "die Landschaft, -en",
    "willkommen",
    "sogenannt-",
    "anschnallen, schnallt an, schnallte an, hat angeschnallt",
    "pauschal",
    "politisch",
    "sobald",
    "wecken, weckt, weckte, hat geweckt (((2qq)))",
    "das Kreuz, -e",
    "anstellen, stellt an, stellte an, hat angestellt",
    "die Anmeldung, -en",
    "anschließen, schließt an, schloss an, hat angeschlossen",
    "um … zu",
    "Prost",
    "die Frist, -en",
    "zurück/zurück-",
    "scharf",
    "die Stadt, ¨-e",
    "das Tempo",
    "beleidigen, beleidigt, beleidigte, hat beleidigt",
    "die Blume, -n",
    "solange",
    "gestern",
    "erst-",
    "das Ei, -er",
    "die Werbung, -en",
    "das Plastik",
    "fördern, fördert, förderte, hat gefördert",
    "klein",
    "der Teilnehmer, -",
    "anfangs",
    "was für ein-",
    "wirken, wirkt, wirkte, hat gewirkt",
    "aller-",
    "allgemein",
    "aufmerksam",
    "dürfen, darf, durfte, hat gedurft (hat dürfen als Modalverb)",
    "die Erzählung, -en",
    "ungewöhnlich",
    "zunächst",
    "(sich) stoßen, stößt, stieß, hat gestoßen",
    "halbtags",
    "die Mehrwertsteuer",
    "zusammen/zusammen-",
    "das Fernsehen",
    "hierher",
    "der Strand, ¨-e",
    "fließend",
    "rein",
    "zurzeit",
    "der Schnupfen",
    "tatsächlich",
    "oft/öfter",
    "zufrieden",
    "bestimmt",
    "unterwegs",
    "schlimm",
    "(sich) umdrehen, dreht um, drehte um, hat umgedreht",
    "der Serviceangestellte, -n",
    "durcheinander",
    "das Modell, -e",
    "zumindest",
    "organisieren, organisiert, organisierte, hat organisiert",
    "zuverlässig",
    "das Rind, -er",
    "der Dienst",
    "der Sitz, -e",
    "schmal",
    "greifen, greift, griff, hat gegriffen",
    "die Zwiebel, -n",
    "schlafen, schläft, schlief, hat geschlafen",
    "sammeln, sammelt, sammelte, hat gesammelt",
    "die Flucht",
    "der Schlüssel, -",
    "die Salbe, -n",
    "die Vase, -n",
    "anerkennen, erkennt an, erkannte an, hat anerkannt",
    "früher/früher-",
    "die Ausfahrt, -en",
    "das Zelt, -e",
    "bremsen, bremst, bremste, hat gebremst",
    "rechtlich",
    "bereits",
    "hoffentlich",
    "die Natur",
    "der Einfluss, ¨-e",
    "zusammenfassen, fasst zusammen, fasste zusammen, hat zusammengefasst",
    "der Lebenslauf, ¨-e",
    "die Katastrophe, -n",
    "der Käse",
    "ausrichten, richtet aus, richtete aus, hat ausgerichtet",
    "üben",
    "die Untersuchung, -en",
    "der Markt, ¨-e",
    "→ A: Stiege",
    "die Anrede, -n",
    "der Konsum",
    "gleichzeitig",
    "der Notausgang, ¨-e",
    "das Ballett, -e",
    "der Mut",
    "der Leser, -",
    "die Beratung",
    "kreativ",
    "nun",
    "entsorgen, entsorgt, entsorgte, hat entsorgt",
    "verschieben, verschiebt, verschob, hat verschoben",
    "→ D: Abitur",
    "all-",
    "der Speisewagen, -",
    "die Zeitung, -en",
    "der Pfeffer",
    "der Nachbar, -n",
    "die Hitze",
    "die Verabredung, -en",
    "die Lippe, -n",
    "die Einwohnerin, -nen",
    "schlank",
    "das Mitglied, -er",
    "aufstehen, steht auf, stand auf, ist aufgestanden",
    "sich erkundigen, erkundigt sich, erkundigte sich, hat sich erkundigt",
    "(sich) setzen, setzt, setzte, hat gesetzt",
    "sehen, sieht, sah, hat gesehen",
    "der Feierabend",
    "die Störung, -en",
    "der Experte, -n",
    "anzeigen, zeigt an, zeigte an, hat angezeigt",
    "zurzeit",
    "das Tennis",
    "üblich",
    "zustimmen, stimmt zu, stimmte zu, hat zugestimmt",
    "statistisch",
    "der Husten",
    "meist(ens)",
    "springen, springt, sprang, ist gesprungen",
    "die (Schlag-)Sahne (D)",
    "sinnlos",
    "das Semester, -",
    "satt",
    "das Training, -s",
    "die Klinik, -en",
    "brechen, bricht, brach, hat gebrochen",
    "der Krimi, -s",
    "das Gewicht, -e",
    "die Eile",
    "das Schwimmbad, ¨-er",
    "der Stift, -e",
    "aufregen, regt auf, regte auf, hat aufgeregt",
    "sinnvoll",
    "die Insel, -n",
    "sportlich",
    "der Krankenpfleger, -",
    "die Mobilität, -en",
    "die Auskunft, ¨-e",
    "die Prüfung, -en",
    "die Reaktion, -en",
    "der Sessel, - (A)",
    "die Weiterbildung, -en",
    "der Sohn, ¨-e",
    "der Gegensatz, ¨-e",
    "das Ufer, -",
    "das Schaufenster, -",
    "(sich) rasieren, rasiert, rasierte, hat rasiert",
    "öffnen, öffnet, öffnete, hat geöffnet",
    "inzwischen",
    "der Müll",
    "der Bescheid, -e",
    "vermissen, vermisst, vermisste, hat vermisst",
    "einschließlich",
    "liefern, liefert, lieferte, hat geliefert",
    "meist-, die meisten",
    "der Jugendliche, -n",
    "taub",
    "der Fleischhauer, -",
    "→ D, CH: Sessel",
    "die Hörerin, -nen",
    "(sich) ärgern, ärgert, ärgerte, hat geärgert",
    "der Hammer, ¨-",
    "bewölkt",
    "der Kiosk, -e",
    "die Uniform, -en",
    "hochladen, lädt hoch, lud hoch, hat hochgeladen",
    "festlegen, legt fest, legte fest, hat festgelegt",
    "heute",
    "auffordern, fordert auf, forderte auf, hat aufgefordert",
    "ersetzen, ersetzt, ersetzte, hat ersetzt",
    "die Jugend",
    "die Zahl, -en",
    "der Park, -s",
    "der Stiefel, -",
    "die Bedeutung, -en",
    "die Praktikantin, -nen",
    "normal",
    "der Tote, -n",
    "(sich) verabreden, verabredet, verabredete, hat verabredet",
    "der Zeitpunkt, e",
    "miteinander",
    "(sich) streiten, streitet, stritt, hat gestritten",
    "reichen, reicht, reichte, hat gereicht",
    "erkennen, erkennt, erkannte, hat erkannt",
    "das Nahrungsmittel, -",
    "der Stadtplan, ¨-e",
    "der Respekt",
    "zentral",
    "der Verkäufer, -",
    "besichtigen, besichtigt, besichtigte, hat besichtigt",
    "positiv",
    "manchmal",
    "die Umwelt",
    "essen, isst, aß, hat gegessen",
    "die Schachtel, -n",
    "das Heim, -e",
    "einig-",
    "die Garantie",
    "die Marmelade, -n (D, A)",
    "ob",
    "der Ordner, -",
    "die Rückfahrt, -en",
    "der Rock, ¨-e",
    "schwitzen, schwitzt, schwitzte, hat geschwitzt",
    "herstellen, stellt her, stellte her, hat hergestellt",
    "funktionieren, funktioniert, funktionierte, hat funktioniert",
    "das Blatt, ¨-er",
    "die Vertretung, -en",
    "die Umleitung, -en",
    "geradeaus",
    "der Arbeitsplatz, ¨-e",
    "die Musik",
    "das Projekt, -e",
    "→ D, CH: probieren",
    "einzahlen, zahlt ein, zahlte ein, hat eingezahlt",
    "anmelden, meldet an, meldete an, hat angemeldet",
    "der Kasten, ¨- (D)",
    "die Theorie, -n",
    "die Minderheit, -en",
    "→ CH: Tram",
    "der Baum, ¨-e",
    "der Braten, -",
    "→ CH: Glace/Glacé",
    "→ A: Paradeiser",
    "→ D: Möhre; CH: Rüebli",
    "sichtbar",
    "intensiv",
    "das Blut",
    "die Zustimmung, -en",
    "die Friseurin, -nen (D, A)",
    "traditionell",
    "verboten",
    "deswegen",
    "als",
    "laut",
    "der Koch, ¨-e",
    "die Terrasse, -n",
    "die Stimme, -n",
    "erfahren, erfährt, erfuhr, hat erfahren",
    "anbieten, bietet an, bot an, hat angeboten",
    "behalten, behält, behielt, hat behalten",
    "feststehen, steht fest, stand fest, ist festgestanden",
    "der Fahrer, -",
    "das Benzin",
    "zuletzt",
    "der Druck",
    "sympathisch",
    "alltäglich",
    "der Pass, ¨-e",
    "die Konfitüre, -n (CH)",
    "die Erhöhung, -en",
    "die Sportlerin, -nen",
    "das Wunder, -",
    "zuerst",
    "die Jause, -n (A)",
    "das Gerät, -e",
    "der Mensch, -en",
    "die e-card (A)",
    "die Geschichte, -n",
    "der Tod",
    "betrunken",
    "roh",
    "sowieso",
    "→ Fahrrad; D, A: Rad",
    "der Gott, ¨-er",
    "die Heimat",
    "der Erdapfel, ¨- (A)",
    "das Formular, -e",
    "stehen, steht, stand, hat/ist gestanden",
    "eckig",
    "beachten, beachtet, beachtete, hat beachtet",
    "bleiben, bleibt, blieb, ist geblieben",
    "der Direktor, -en",
    "die Oper, -n",
    "tun, tut, tat, hat getan",
    "→ D: die Versichertenkarte",
    "(sich) waschen, wäscht, wusch, hat gewaschen",
    "das Verbot, -e",
    "erinnern, erinnert, erinnerte, hat erinnert",
    "die Panne, -n",
    "ausfallen, fällt aus, fiel aus, ist ausgefallen",
    "recht",
    "die Straßenbahn, -en",
    "eintreten, tritt ein, trat ein, ist eingetreten",
    "warten, wartet, wartete, hat gewartet",
    "die Fußgängerin, -nen",
    "der Rucksack, ¨-e",
    "hoch",
    "die Summe, -n",
    "unheimlich",
    "übernehmen, übernimmt, übernahm, hat übernommen.",
    "der Lehrling, -e",
    "der Sack, ¨-e",
    "verhindern, verhindert, verhinderte, hat verhindert",
    "die Schulter, -n",
    "ausmachen, macht aus, machte aus, hat ausgemacht",
    "der Krankenwagen, -",
    "der Neffe, -n",
    "günstig",
    "der Verein, -e",
    "der Gehsteig (D, A)",
    "die Angehörige, -n",
    "→ CH: Führerausweis",
    "nirgendwo",
    "verwechseln, verwechselt, verwechselte, hat verwechselt",
    "die Runde, -n",
    "das Bier",
    "fliehen, flieht, floh, ist geflohen",
    "meinetwegen",
    "schwimmen, schwimmt, schwamm, ist geschwommen",
    "vergnügt",
    "unterrichten, unterrichtet, unterrichtete, hat unterrichtet",
    "das Mal, -e",
    "die Chance, -n",
    "außerhalb",
    "→ Kiste (A, D)",
    "halten, hält, hielt, hat gehalten",
    "der Teller, -",
    "testen, testet, testete, hat getestet",
    "die Zukunft",
    "die Übung, -en",
    "unterstreichen, unterstreicht, unterstrich, hat unterstrichen",
    "der Fußball, ¨-e",
    "die Tote, -n",
    "hässlich",
    "außen",
    "heiraten, heiratet, heiratete, hat geheiratet",
    "dienen, dient, diente, hat gedient",
    "die Eisenbahn, -en",
    "empfangen, empfängt, empfing, hat empfangen",
    "das Sonderangebot, -e",
    "Traum-",
    "die Nachspeise, -n (D, A)",
    "abonnieren, abonniert, abonnierte, hat abonniert",
    "die Ehe, -n",
    "sondern",
    "voll",
    "besuchen, besucht, besuchte, hat besucht",
    "gewohnt",
    "der Finger, -",
    "der Blitz, -e",
    "der Fußgänger, -",
    "→ Stock",
    "der Glückwunsch, ¨-e",
    "veröffentlichen, veröffentlicht, veröffentlichte, hat veröffentlicht",
    "allerdings",
    "werden, wird, wurde, ist geworden",
    "heim",
    "klopfen, klopft, klopfte, hat geklopft",
    "der Künstler, -",
    "die Bankomat-Karte, -n (A)",
    "das Tier, -e",
    "interessant",
    "die Kreditkarte, -n",
    "die Farbe, -n",
    "der Eingang, ¨-e",
    "beweisen, beweist, bewies, hat bewiesen",
    "der Kellner, -",
    "tief",
    "die Bluse, -n",
    "salzig",
    "die Krankenkasse, -n",
    "ernst",
    "die Leistung, -en",
    "geheim",
    "doch",
    "verurteilen, verurteilt, verurteilte, hat verurteilt",
    "das Gefängnis, -se",
    "überall",
    "die Nichte, -n",
    "beschreiben, beschreibt, beschrieb, hat beschrieben",
    "→ D, CH: Treppenhaus",
    "das Glas, ¨-er",
    "die Garderobe, -n",
    "ideal",
    "die Bedienungsanleitung, -en",
    "umtauschen, tauscht um, tauschte um, hat umgetauscht",
    "Bescheid sagen",
    "die Einbrecherin, -nen",
    "die Lösung, -en",
    "das Ausland",
    "erleichtern, erleichtert, erleichterte, hat erleichtert",
    "die Bürgerin, -nen",
    "sich kümmern, kümmert sich, kümmerte sich, hat sich gekümmert",
    "die Geduld",
    "der Hof, ¨-e",
    "verlangen, verlangt, verlangte, hat verlangt",
    "die Begründung, -en",
    "reden, redet, redete, hat geredet",
    "der Angehörige, -n",
    "der Anruf, -e",
    "selbst",
    "finanzieren, finanziert, finanzierte, hat finanziert",
    "vorbei/vorbei-",
    "die Zahncreme/-pasta",
    "schwach",
    "das Rad, ¨-er (D, A)",
    "künstlich",
    "nennen, nennt, nannte, hat genannt",
    "die Orange, -n",
    "die Chipkarte, -n",
    "die Coiffeuse, -n (CH)",
    "der Stoff, -e",
    "fleißig",
    "der Wecker, -",
    "arm",
    "der Stil, -e",
    "die Stufe, -n",
    "die Mitte",
    "die Bestätigung, -en",
    "eindeutig",
    "in",
    "bekommen, bekommt, bekam, hat bekommen",
    "der Start, -s",
    "stattfinden, findet statt, fand statt, hat stattgefunden",
    "das Vorstellungsgespräch, -e",
    "die Couch, -s",
    "die Teilnehmerin, -nen",
    "das Obst (D, A)",
    "beruflich",
    "spitz",
    "das Mineralwasser",
    "preiswert",
    "halb",
    "das Frühstück",
    "offenbar",
    "total",
    "die Verwandte, -n",
    "die Gymnastik",
    "drüben",
    "singen, singt, sang, hat gesungen",
    "tanken, tankt, tankte, hat getankt",
    "der Strafzettel, -",
    "die Professorin, -nen",
    "befreit",
    "der Student, -en",
    "deshalb",
    "passen, passt, passte, hat gepasst",
    "dahin",
    "spät",
    "die Verletzung, -en",
    "hoffen, hofft, hoffte, hat gehofft",
    "die Sehenswürdigkeit, -en",
    "mittlerweile",
    "der Augenblick, -e",
    "original",
    "nur",
    "das System, -e",
    "das Studium, Studien",
    "mitten",
    "das Verkehrsmittel, -",
    "der Regen",
    "→ Altenheim",
    "die Fläche, -n",
    "die Kritik, -en",
    "die Karte, -n",
    "der Bau, Bauten",
    "der Mitarbeiter, -",
    "schütteln, schüttelt, schüttelte, hat geschüttelt",
    "die Pöstlerin, -nen (CH)",
    "normalerweise",
    "die Leserin, -nen",
    "durstig",
    "(sich) wünschen, wünscht, wünschte, hat gewünscht",
    "los/los-",
    "ungefähr",
    "heutig-",
    "die Medizin",
    "die Semmel, -n (A)",
    "entlassen, entlässt, entließ, hat entlassen",
    "vor",
    "dünn",
    "stoppen, stoppt, stoppte, hat gestoppt",
    "die Flasche, -n",
    "nach",
    "vertreten, vertritt, vertrat, hat vertreten",
    "kürzlich",
    "ganz",
    "der Vermieter, -",
    "ankommen, kommt an, kam an, ist angekommen",
    "die Entschuldigung, -en",
    "das Restaurant, -s",
    "gleich",
    "der Stock",
    "der Meister, -",
    "die Einführung, -en",
    "die Alternative, -n",
    "erfolgreich",
    "→ A: Stiegenhaus",
    "der Arzt, ¨-e",
    "eventuell",
    "auch",
    "die Arbeitsstelle, -n",
    "der Strom",
    "der Abschluss, ¨-e",
    "die Zeitschrift, -en",
    "die Fähre, -n",
    "→ A: Kuvert; CH: Couvert",
    "wie viel(e)",
    "Golf, das Golfspiel",
    "das Poulet, -s (CH)",
    "das Mädchen, -",
    "die Einrichtung, -en",
    "ewig",
    "beraten, berät, beriet, hat beraten",
    "die Wissenschaft, -en",
    "die Politik",
    "eben",
    "faul",
    "der Sportler, -",
    "das Souvenir, -s",
    "die Nähe",
    "der Arm, -e",
    "beginnen, beginnt, begann, hat begonnen",
    "genügen, genügt, genügte, hat genügt",
    "verschmutzen, verschmutzt, verschmutzte, hat verschmutzt",
    "die Unterstützung, -en",
    "häufig",
    "das Ziel, -e",
    "besitzen, besitzt, besaß, hat besessen",
    "der Briefträger,",
    "das Haus, ¨-er",
    "geben, gibt, gab, hat gegeben",
    "das/der Zvieri/Znüni, -s (CH)",
    "die Tüte, -n",
    "das Kaffeehaus, ¨-er (A)",
    "der Drucker, -",
    "stammen, stammt, stammte, hat gestammt",
    "erleben, erlebt, erlebte, hat erlebt",
    "die Schwierigkeit, -en",
    "lustig",
    "der Unterricht",
    "die Angestellte, -n",
    "die Szene, -n",
    "kaputtgehen",
    "das Land, ¨-er",
    "vereinbaren, vereinbart, vereinbarte, hat vereinbart",
    "akzeptieren, akzeptiert, akzeptierte, hat akzeptiert",
    "ankündigen, kündigt an, kündigte an, hat angekündigt",
    "→ Metzger",
    "die Organisation, -en",
    "ausreichen, reicht aus, reichte aus, hat ausgereicht",
    "der Umzug, ¨-e",
    "die Entlassung, -en",
    "ausstellen, stellt aus, stellte aus, hat ausgestellt",
    "die Geldbörse, -n (A)",
    "statt",
    "die Hoffnung, -en",
    "die Gewohnheit, -en",
    "dauernd",
    "der Zeuge, -n",
    "der Prospekt, -e",
    "zuständig",
    "landen, landet, landete, ist gelandet",
    "der Schluss",
    "das Altenheim, -e",
    "die Umweltverschmutzung, -en",
    "der Dank",
    "das Produkt, -e",
    "die Rechnung, -en",
    "die Bank, -en",
    "analysieren, analysiert, analysierte, hat analysiert",
    "Groß-",
    "die Liebe",
    "wo",
    "ausfüllen, füllt aus, füllte aus, hat ausgefüllt",
    "das Wörterbuch, ¨-er",
    "das Schwammerl, -n (A)",
    "die Lüge, -n",
    "die Ermäßigung, -en",
    "die Frau, -en",
    "gründen, gründet, gründete, hat gegründet",
    "entweder ... oder",
    "das Original, -e",
    "digital",
    "oder",
    "blass",
    "ziehen, zieht, zog, hat/ist gezogen",
    "dauern, dauert, dauerte, hat gedauert",
    "wichtig",
    "die Schlange, -n",
    "→ A: Dose",
    "der Einwohner, -",
    "der Dieb, -e",
    "die Grafik, -en",
    "nächst-",
    "pro",
    "fassen, fasst, fasste, hat gefasst",
    "reservieren, reserviert, reservierte, hat reserviert",
    "die Kosten (Pl.)",
    "aufnehmen, nimmt auf, nahm auf, hat aufgenommen",
    "theoretisch",
    "nachdenken, denkt nach, dachte nach, hat nachgedacht",
    "das Verhalten",
    "das Velo, -s (CH)",
    "das Fenster, -",
    "→ D, A: Führerschein",
    "die Reform, -en",
    "das Feld, -er",
    "vielleicht",
    "das Zeichen, -",
    "die Feier, -n",
    "duzen, duzt, duzte, hat geduzt",
    "hören, hört, hörte, hat gehört",
    "der Mangel, ¨-",
    "sämtliche",
    "die Creme, -n/-s",
    "die Schrift, -en",
    "per",
    "die Familie, -n",
    "mischen, mischt, mischte, hat gemischt",
    "der (Back-)Ofen, ¨- (D, CH)",
    "der Schriftsteller, -",
    "wechseln, wechselt, wechselte, hat gewechselt",
    "geehrt",
    "damit",
    "der Täter, -",
    "der Besuch, -e",
    "der Haushalt, -e",
    "neblig",
    "sterben, stirbt, starb, ist gestorben",
    "das Ding, -e",
    "zerstören, zerstört, zerstörte, hat zerstört",
    "die Universität, -en",
    "die Butter",
    "der Profi, -s",
    "das Papier, -e",
    "das Ehepaar, -e",
    "gefallen, gefällt, gefiel, hat gefallen",
    "gleichfalls",
    "das Portemonnaie/Portmonee, -s (D, CH)",
    "der Erwachsene, -n",
    "der Schmuck",
    "elegant",
    "die Margarine",
    "der Tourismus",
    "Bio-",
    "bedienen, bedient, bediente, hat bedient",
    "die Kollegin, -nen",
    "wachsen, wächst, wuchs, ist gewachsen",
    "rennen, rennt, rannte, ist gerannt",
    "der Kaffee",
    "→ CH: Pfanne",
    "der Transport, -e",
    "die Zigarette, -n",
    "das Öl, -e",
    "ärgerlich",
    "die Reinigung, -en",
    "menschlich",
    "weich",
    "der Bogen, -/¨-",
    "der Polizist, -en",
    "männlich",
    "wahrscheinlich",
    "der Abfall, ¨-e",
    "teilnehmen, nimmt teil, nahm teil, hat teilgenommen",
    "die Gewalt, -en",
    "der Migrant, -en",
    "der Tipp, -s",
    "fernsehen, sieht fern, sah fern, hat ferngesehen",
    "entwickeln, entwickelt, entwickelte, hat entwickelt",
    "zubereiten, bereitet zu, bereitete zu, hat zubereitet",
    "die Gratulation, -en",
    "schwer",
    "die Rede, -n",
    "außerdem",
    "die Spielerin, -nen",
    "vernünftig",
    "die Scheibe, -n",
    "wandern, wandert, wanderte, ist gewandert",
    "→ D: (Schlag-)Sahne; CH: (Schlag-)Rahm",
    "natürlich",
    "die Betriebsrätin, -nen",
    "die Phantasie/Fantasie, -n",
    "der Wirt, -e",
    "die Reportage, -n",
    "leicht",
    "die Lust",
    "die Schauspielerin, -nen",
    "schalten, schaltet, schaltete, hat geschaltet",
    "die Tätigkeit, -en",
    "→ D: Kloß",
    "die Antwort, -en",
    "die Batterie, -n",
    "frei",
    "möchten, möchte, mochte, hat gemocht",
    "(sich) duschen, duscht, duschte, hat geduscht",
    "der Schauspieler, -",
    "denken, denkt, dachte, hat gedacht",
    "die Sprache, -n",
    "die Halbpension",
    "der Alkohol",
    "das Tor, -e",
    "die Grippe",
    "das Picknick, -s die Pille, -n",
    "die Operation, -en",
    "das Beispiel, -e",
    "die Täterin, -nen",
    "das Mehl",
    "die Anzahl, -en",
    "der Blick, -e",
    "der Grill",
    "→ D, A: Straßenbahn",
    "die Banane, -n",
    "fett",
    "der Flohmarkt, ¨-e",
    "deutlich",
    "ernähren, ernährt, ernährte, hat ernährt",
    "der Katalog, -e",
    "das Zimmer, -",
    "die Bäckerei, -en",
    "eilig",
    "die Toilette, -n",
    "die Entfernung, -en",
    "rechts",
    "der Imbiss, -e (D)",
    "fordern, fordert, forderte, hat gefordert",
    "der Teil, -e",
    "das Brötli, - (CH)",
    "anrufen, ruft an, rief an, hat angerufen",
    "der Passagier, -e",
    "die Lehrerin, -nen",
    "die Mitarbeiterin, -nen",
    "die Münze, -n",
    "Ferien-",
    "das Gemüse",
    "stinken, stinkt, stank, hat gestunken",
    "der Satz, ¨-e",
    "spazieren gehen, geht spazieren, ging spazieren, ist spazieren gegangen",
    "die Beamtin, -nen",
    "der Steward, -s",
    "nähen, näht, nähte, hat genäht",
    "das Treppenhaus, ¨-er (D, CH)",
    "direkt",
    "je",
    "→ CH: Früchte",
    "der Hals, ¨-e",
    "einverstanden",
    "→ A, CH: Bancomat/Bankomat",
    "her/her-",
    "die Notaufnahme, -n",
    "der Stecker, -",
    "aktiv",
    "verlängern, verlängert, verlängerte, hat verlängert",
    "schweigen, schweigt, schwieg, hat geschwiegen",
    "einsetzen, setzt ein, setzte ein, hat eingesetzt",
    "die Bewohnerin, -nen",
    "→ D, CH: Aprikose",
    "weder … noch",
    "die Beschreibung, -en",
    "das Auge, -n",
    "die Scheidung, -en",
    "bitter",
    "tanzen, tanzt, tanzte, hat getanzt",
    "hageln, hagelt, hagelte, hat gehagelt",
    "bringen, bringt, brachte, hat gebracht",
    "→ CH: grillieren",
    "machen, macht, machte, hat gemacht",
    "der Vorname, -n",
    "studieren, studiert, studierte, hat studiert",
    "die Serie, -n",
    "→ D, A: Fahrkarte",
    "hinterlassen, hinterlässt, hinterließ, hat hinterlassen",
    "der Umtausch, ¨-e",
    "der Wald, ¨-er",
    "genehmigen, genehmigt, genehmigte, hat genehmigt",
    "melden, meldet, meldete, hat gemeldet",
    "die Ärztin, -nen",
    "der Vertrag, ¨-e",
    "die Rücksicht, -en",
    "die Miete, -n",
    "das Bad, ¨-er",
    "die Drogerie, -n",
    "klingen, klingt, klang, hat geklungen",
    "selb-",
    "die Stunde, -n",
    "der Hauptbahnhof, ¨-e",
    "haltbar",
    "die Schwangerschaft, -en",
    "freiwillig",
    "→ D, CH: Rentner",
    "die Lampe, -n",
    "der Ober, - (D, A)",
    "die Kellnerin, -nen",
    "erfordern, erfordert, erforderte, hat erfordert",
    "das Pech",
    "die Rolle, -n",
    "tauchen, taucht, tauchte, ist/hat getaucht",
    "die Tastatur, -en",
    "stark",
    "der Maler, -",
    "die Schere, -n",
    "der Versuch, -e",
    "der Sinn",
    "begegnen, begegnet, begegnete, ist begegnet",
    "→ D: Klassenarbeit",
    "zählen, zählt, zählte, hat gezählt",
    "die Linie, -n",
    "die Zutaten (Pl.)",
    "kräftig",
    "dringend",
    "gewinnen, gewinnt, gewann, hat gewonnen",
    "lächeln, lächelt, lächelte, hat gelächelt",
    "unterschiedlich",
    "die Studentin, -nen",
    "die Verantwortung",
    "→ Brieftasche; D, CH: Portemonnaie/Portmonee",
    "die Abwartin, -nen (CH)",
    "schriftlich",
    "das Salz, -e",
    "beschränken",
    "selber",
    "die Langeweile",
    "stimmen, stimmt, stimmte, hat gestimmt",
    "leihen, leiht, lieh, hat geliehen",
    "der Verlag, -e (A: ¨-e)",
    "planen, plant, plante, hat geplant",
    "langweilig",
    "der Zuschauer, -",
    "der Rest, -e",
    "das Wohnzimmer, -",
    "die Distanz, -en",
    "sein, ist, war, ist gewesen",
    "der Sekretär, -e",
    "→ D, CH: Portemonnaie/Portmonee; A: Geldbörse",
    "das Foto, -s",
    "verwandt",
    "der Kopierer, -",
    "der Wagen, -",
    "die Wolle",
    "der Betriebsrat, ¨-e",
    "der Brief, -e",
    "aufhalten, hält auf, hielt auf, hat aufgehalten",
    "die Einladung, -en",
    "die Portion, -en",
    "die Länge",
    "unterbrechen, unterbricht, unterbrach, hat unterbrochen",
    "der Hausmann",
    "das Gold",
    "die Kassette, -n",
    "herein-, rein-",
    "betrügen, betrügt, betrog, hat betrogen",
    "die Gelegenheit, -en",
    "die Bewerbung, -en",
    "der Teppich, -e",
    "der Geschmack",
    "die Realität, -en",
    "rückwärts",
    "umso",
    "S-Bahn, -en",
    "fair",
    "→ D, A: in Pension gehen/sein; D: in Rente gehen/sein",
    "das Spielzeug, -e",
    "aktuell",
    "fällig",
    "benötigen, benötigt, benötigte, hat benötigt",
    "die Möglichkeit, -en",
    "einfach",
    "die Versichertenkarte, -n (D)",
    "das Praktikum, Praktika",
    "der Fachmann",
    "völlig",
    "der Nachteil, -e",
    "der Rasen, -",
    "geboren werden, wird geboren, wurde geboren, ist geboren worden",
    "sofort",
    "der Gruß, ¨-e",
    "warnen, warnt, warnte, hat gewarnt",
    "groß",
    "die Erinnerung, -en",
    "das Wort, -e",
    "der Schaden, ¨-",
    "ständig",
    "die U-Bahn, -en",
    "die Lage",
    "die Absenderin, -nen",
    "das Zentrum, Zentren",
    "fremd",
    "die Steuer, -n",
    "der Schmutz",
    "die Recherche, -n",
    "die Gesellschaft, -en",
    "das Billett, -e/-s",
    "angeben, gibt an, gab an, hat angegeben",
    "genau",
    "die Presse",
    "der Arbeiter, -",
    "→ D, A: grillen",
    "äußerlich",
    "kein-",
    "der Wert, -e",
    "verabredet",
    "derselbe, dieselbe, dasselbe",
    "gesamt-/Gesamt-",
    "rufen, ruft, rief, hat gerufen",
    "die Baustelle, -n",
    "die Stimmung, -en",
    "die Nudel, -n",
    "eröffnen, eröffnet, eröffnete, hat eröffnet",
    "das Studio, -s",
    "die Konferenz, -en",
    "die Ansage, -n",
    "der Aufzug, ¨-e (D, A)",
    "die Werkstatt, ¨-en",
    "→ CH: Billett",
    "→ D, A: Obst",
    "der Körper, -",
    "→ CH: Coiffeur",
    "diesmal",
    "die Daten (Plural)",
    "einladen, lädt ein, lud ein, hat eingeladen",
    "drücken, drückt, drückte, hat gedrückt",
    "gegenüber",
    "der Import, -e",
    "voraussichtlich",
    "die Zusammenarbeit",
    "die Reihenfolge, -n",
    "der Text, -e",
    "→ A, CH: Pension",
    "die Strafe, -n",
    "die Treppe, -n (D, CH)",
    "das Gepäck",
    "insgesamt",
    "annehmen, nimmt an, nahm an, hat angenommen",
    "der Streit",
    "fröhlich",
    "super",
    "gerecht",
    "die Karotte, -n",
    "ausgebildet",
    "sich weigern, weigert sich, weigerte sich, hat sich geweigert",
    "der Metzger, -",
    "aufladen, lädt auf, lud auf, hat aufgeladen",
    "der Bildschirm, -e",
    "die Krankenschwester, -n",
    "speziell",
    "(sich) verbrennen, verbrennt, verbrannte, hat verbrannt",
    "wenn",
    "der Buchstabe, -n",
    "der Empfänger, -",
    "zu",
    "das Zuhause",
    "das Klavier, -e",
    "die Architektin, -nen",
    "blitzen, blitzt, blitzte, hat geblitzt",
    "kopieren",
    "der Zuschlag, ¨-e",
    "der Opa, -s",
    "die Mülltonne, -n",
    "bald",
    "ander-",
    "der Schüler, -",
    "unternehmen, unternimmt, unternahm, hat unternommen",
    "der Eindruck, ¨-e",
    "froh",
    "besetzen, besetzt, besetzte, hat besetzt",
    "zuschauen, schaut zu, schaute zu, hat zugeschaut",
    "solch-",
    "die Kursleiter, -nen",
    "der Lärm",
    "→ Fahrrad; CH: Velo",
    "die Herkunft",
    "sich wundern, wundert sich, wunderte sich, hat sich gewundert",
    "die Station, -en",
    "stecken, steckt, steckte, hat gesteckt",
    "das Kostüm, -e",
    "schauen, schaut, schaute, hat geschaut",
    "→ Altersheim",
    "die Fortsetzung, -en",
    "abnehmen, nimmt ab, nahm ab, hat abgenommen",
    "lang",
    "heraus-, raus- (heraus-) finden, findet heraus, fand heraus, hat herausgefunden",
    "finanziell",
    "entgegenkommen",
    "versäumen, versäumt, versäumte, hat versäumt",
    "→ CH: Trottoir",
    "beinahe",
    "nah(e)",
    "angenehm",
    "der Kuss, ¨-e",
    "die Nummer, -n",
    "das Hend(e)l, - (A)",
    "das Publikum",
    "die Halle, -n",
    "die Trainerin, -nen",
    "der Bub, -en (A, CH)",
    "die Marille, -n (A)",
    "der Kandidat, -en",
    "richtig",
    "rauchen, raucht, rauchte, hat geraucht",
    "pflegen, pflegt, pflegte, hat gepflegt",
    "einbrechen, bricht ein, brach ein, ist eingebrochen",
    "der Fortschritt, -e",
    "die Vorbereitung, -en",
    "schicken, schickt, schickte, hat geschickt",
    "das Glück",
    "der Sieger, -",
    "die Mutter, ¨-",
    "kompliziert",
    "waagerecht",
    "anschaffen, schafft an, schaffte an, hat angeschafft",
    "der Pöstler, -",
    "nicht",
    "verreisen, verreist, verreiste, ist verreist",
    "die Politikerin, -nen",
    "protestieren, protestiert, protestierte, hat protestiert",
    "(sich) zwingen, zwingt, zwang, hat gezwungen",
    "der Hinweise, -e",
    "einmal",
    "→ D: Hähnchen/Hühnchen; CH: Poulet",
    "die Einzelheit, -en",
    "verdächtig",
    "die Nachricht, -en",
    "gelingen, gelingt, gelang, ist gelungen",
    "der Enkel, -",
    "die Aktivität, -en",
    "die Technik, -en",
    "gucken, guckt, guckte, hat geguckt",
    "mager",
    "die Passagierin, -nen",
    "der Zustand, ¨-e",
    "reich",
    "dort",
    "der Honig",
    "berufstätig",
    "nötig",
    "der Mantel, ¨-",
    "aufwärts",
    "abhängen, hängt ab, hing ab, hat abgehangen (von)",
    "die Arbeit, -en",
    "die Bitte, -n",
    "der Kindergarten, ¨-",
    "die Welt",
    "→ D: Imbiss; CH: Znüni/Zvieri",
    "trocken",
    "das Fundbüro, -s",
    "der Kuchen, -",
    "fangen, fängt, fing, hat gefangen",
    "das Taschentuch, ¨-er",
    "die Einbahnstraße, -n",
    "stolz",
    "nass",
    "drucken, druckt, druckte, hat gedruckt",
    "trainieren, trainiert, trainierte, hat trainiert",
    "verzichten, verzichtet, verzichtete, hat verzichtet",
    "komplett",
    "der Stempel, -",
    "mittler-",
    "die Wirkung, -en",
    "die Hälfte, -n",
    "das Zeugnis, -se",
    "letzt-",
    "früh",
    "der Stein, -e",
    "die Ausnahme, -n",
    "sagen, sagt, sagte, hat gesagt",
    "tippen, tippt, tippte, hat getippt",
    "sich ereignen, ereignet sich, ereignete sich, hat sich ereignet",
    "das Gleis, -e",
    "das Werk, -e",
    "das Magazin, -e",
    "das Lager, -",
    "→ Kellner; D, A: Ober",
    "Lieblings-",
    "gern/gerne",
    "Schwieger-",
    "der Beleg, -e",
    "langsam",
    "die Doktorin, -nen",
    "tolerant",
    "überweisen, überweist, überwies, hat überwiesen",
    "das Grundstück, -e",
    "das Verkehrszeichen, -",
    "das Bein, -e",
    "abhängig",
    "der Anspruch, ¨-e",
    "immer",
    "die Frage, -n",
    "(sich) unterhalten, unterhält, unterhielt, hat unterhalten",
    "die Gruppe, -n",
    "das Krankenhaus, ¨-er",
    "das Brot, -e",
    "umziehen, zieht um, zog um, ist umgezogen",
    "der (Schlag-)Rahm (CH)",
    "bestehen, besteht, bestand, hat bestanden",
    "das Museum, Museen",
    "die Ernte, -n",
    "sonnig",
    "die Person, -en",
    "die Milch",
    "das Eis (D, A)",
    "das Gericht, -e",
    "schaden, schadet, schadete, hat geschadet",
    "die Büchse, -n (D, CH)",
    "das Gespräch, -e",
    "atmen, atmet, atmete, hat geatmet",
    "→ Sprechstunde",
    "populär",
    "das Boot, -e",
    "→ CH: Abwart",
    "der Grund, ¨-e",
    "ober-",
    "der Zufall, ¨-e",
    "die Cousine, -n",
    "der Durchschnitt, -e",
    "einsam",
    "die Hütte, -n",
    "→ Streichholz; A: Zünder",
    "die Wärme",
    "→ D: Karneval; CH: Fasnacht",
    "widersprechen, widerspricht, widersprach, hat widersprochen",
    "nie",
    "verschwinden, verschwindet, verschwand, ist verschwunden",
    "die Gebühr, -en",
    "das Kennzeichen, -",
    "süß",
    "das Fahrzeug, -e",
    "die Schüssel, -n",
    "einrichten, richtet ein, richtete ein, hat eingerichtet",
    "heiß",
    "das Kraftfahrzeug, -e",
    "erkältet",
    "die Direktorin, -nen",
    "das Schloss, ¨-er",
    "→ Kartoffel",
    "die Erklärung, -en",
    "um",
    "weshalb",
    "die Fernbedienung, -en",
    "drin, drinnen",
    "die Jugendherberge, -n",
    "die Spur, -en",
    "die Studie, -n",
    "musikalisch",
    "ursprünglich",
    "tot",
    "die Angabe,-n",
    "die Gabel, -n",
    "müssen, muss, musste, hat gemusst (hat müssen als Modalverb)",
    "der Tagesablauf, ¨-e",
    "die Kopie, -n",
    "die Pflicht, -en",
    "der Gegenstand, ¨-e",
    "hängen, hängt, hing/hängte, hat gehangen/gehängt",
    "der Verdacht",
    "halt",
    "einzig-",
    "die Fahrkarte, -n",
    "ansehen, sieht an, sah an, hat angesehen",
    "der Cousin, -s",
    "sich konzentrieren, konzentriert sich, konzentrierte sich, hat sich konzentriert",
    "der Faktor, -en",
    "→ A: Hend(e)l; Poulet, -s (CH)",
    "das Geheimnis, -se",
    "die Besprechung, -en",
    "die/das Glace/Glacé, -n (CH)",
    "vergrößern, vergrößert, vergrößerte, hat vergrößert",
    "überholen, überholt, überholte, hat überholt",
    "der Auftrag, ¨-e",
    "sicher",
    "blind",
    "minimal",
    "mild",
    "die Reihe, -n",
    "die Hilfe",
    "die Nase, -n",
    "die Wanderung, -en",
    "die Spezialistin, -nen",
    "der Wohnort, -e",
    "alternativ",
    "überqueren, überquert, überquerte, hat überquert",
    "der Ausländer, -",
    "→ A: kosten",
    "der Rand, ¨-er",
    "die Flüssigkeit, -en",
    "sich beeilen, beeilt sich, beeilte sich, hat sich beeilt",
    "das Vergnügen, -",
    "national/national-",
    "nebenbei",
    "die Forschung, -en",
    "grillieren, grilliert, grillierte, hat grilliert (CH)",
    "der Laster, -",
    "→ A, CH: Bub",
    "der Bruder, ¨-",
    "einschalten, schaltet ein, schaltete ein, hat eingeschaltet",
    "der Sand",
    "das Wetter",
    "liegen, liegt, lag, hat/ist gelegen",
    "der Fahrplan, ¨-e",
    "damals",
    "aussehen, sieht aus, sah aus, hat ausgesehen",
    "das Wort, ¨-er",
    "das Bild, -er",
    "der Profisportler, -",
    "der Sender, -",
    "aufführen, führt auf, führte auf, hat aufgeführt",
    "auflösen, löst auf, löste auf, hat aufgelöst",
    "nämlich",
    "→ D, A: Rad; CH: Velo",
    "der Kranke, -n",
    "der Chef, -s",
    "die Brücke, -n",
    "ausländisch",
    "kennen, kennt, kannte, hat gekannt",
    "→ Karotte; D: Möhre",
    "die Grenze, -n",
    "→ D: (Schlag-)Sahne, A: (Schlag-)Obers",
    "gegen",
    "die Infektion, -en",
    "das Apartment, -s",
    "die Schülerin, -nen",
    "fertig",
    "die Zuhörerin, -nen",
    "die Festplatte, -n",
    "der Einkauf, ¨-e",
    "der Witz, -e",
    "das Vertrauen",
    "der Mund, ¨-er",
    "das Lexikon, -Lexika",
    "der Bauernhof, ¨-e",
    "bis",
    "(sich etwas) kaufen, kauft, kaufte, hat gekauft",
    "der Patient, -en",
    "einnehmen, nimmt ein, nahm ein, hat eingenommen",
    "→ A: Faschierte",
    "erreichen, erreicht, erreichte, hat erreicht",
    "→ A: Pensionist",
    "privat",
    "reif",
    "der Richter, -",
    "jeweils",
    "die Kette, -n",
    "realistisch",
    "umgehen, geht um, ging um, ist umgegangen",
    "freundlich",
    "die Nachfrage, -n",
    "leiten, leitet, leitete, hat geleitet",
    "der Platz, ¨-e",
    "produzieren, produziert, produzierte, hat produziert",
    "leisten, leistet, leistete, hat geleistet",
    "erstellen, erstellt, erstellte, hat erstellt",
    "mieten, mietet, mietete, hat gemietet",
    "der Export, -e",
    "das Paket, -e",
    "der Krieg, -e",
    "→ D, CH: Schrank",
    "der Beitrag, ¨-e",
    "sich bemühen, bemüht, bemühte, hat bemüht",
    "der Anwalt, ¨-e",
    "festsetzen, setzt fest, setzte fest, hat festgesetzt",
    "schätzen, schätzt, schätzte, hat geschätzt",
    "(sich) verbessern, verbessert, verbesserte, hat verbessert",
    "der Freund, -e",
    "die Zahlung, -en",
    "der Ausdruck, ¨-e",
    "der Spieler, -",
    "die Briefmarke, -n",
    "seit",
    "der Bleistift, -e",
    "die Tankstelle, -n",
    "die Nadel, -n",
    "nachher",
    "irgendwann",
    "umgekehrt",
    "das Laufwerk, -e",
    "die Gebrauchsanweisung, -en",
    "versuchen, versucht, versuchte, hat versucht",
    "die Tatsache, -n",
    "flach",
    "lesen, liest, las, hat gelesen",
    "bieten, bietet, bot, hat geboten",
    "das Ergebnis, -se",
    "bestellen, bestellt, bestellte, hat bestellt",
    "legen, legt, legte, hat gelegt",
    "der Gedanke, -n",
    "süchtig",
    "die U-Bahn, -en",
    "offen",
    "das Ereignis, -se",
    "vergeblich",
    "der Professor, -en",
    "tauschen, tauscht, tauschte, hat getauscht",
    "fragen, fragt, fragte, hat gefragt",
    "einziehen, zieht ein, zog ein, ist eingezogen",
    "konsumieren, konsumiert, konsumierte, hat konsumiert",
    "regional",
    "bluten, blutet, blutete, hat geblutet",
    "der Zoo, -s",
    "das Hemd, -en",
    "irgendirgendein",
    "dicht",
    "vergleichen, vergleicht, verglich, hat verglichen",
    "die Wunde, -n",
    "vorkommen, kommt vor, kam vor, ist vorgekommen",
    "der Muskel, -n",
    "→ A: Fleischhauer",
    "die Rückkehr",
    "schreien, schreit, schrie, hat geschrien",
    "ergänzen, ergänzt, ergänzte, hat ergänzt",
    "die Vorsicht",
    "der Bauer, -n",
    "der Wohnort, -e",
    "realisieren, realisiert, realisierte, hat realisiert",
    "das Geschäft, -e",
    "glauben, glaubt, glaubte, hat geglaubt",
    "der Stuhl, ¨-e",
    "die Träne, -n",
    "das Gewissen",
    "entlang",
    "regnen, es regnet, es regnete, es hat geregnet",
    "das Motorrad, ¨-er",
    "das Gesetz, -e",
    "der Appetit",
    "das Metall, -e",
    "sich umziehen, zieht sich um, zog sich um, hat sich umgezogen",
    "die Erfahrung, -en",
    "leider",
    "raten, rät, riet, hat geraten",
    "träumen, träumt, träumte, hat geträumt",
    "die Jugendliche, -nen",
    "der Angestellte, -n",
    "die Diskothek, -en/Disko, -s",
    "so viel/so viel wie",
    "übrig",
    "Achtung!",
    "ansprechen, spricht an, sprach an, hat angesprochen",
    "die Meinung, -en",
    "das Faschierte (A)",
    "stehlen, stiehlt, stahl, hat gestohlen",
    "verrückt",
    "fortsetzen, setzt fort, setzte fort, hat fortgesetzt",
    "das Kapitel, -",
    "die Datei, -en",
    "die Haut",
    "der Alarm, -e",
    "die Information, -en",
    "die Annonce, -n",
    "rechnen, rechnet, rechnete, hat gerechnet",
    "wohnen, wohnt, wohnte, hat gewohnt",
    "die Pension, -en (A, CH)",
    "der Sozialarbeiter, -",
    "die Tafel, -n",
    "verständlich",
    "→ Streichholz; Zündholz",
    "die Arbeiterin, -nen",
    "die Sozialarbeiterin, -nen",
    "die Arbeitserlaubnis",
    "der Fernseher, -",
    "→ A: e-card",
    "fotografieren, fotografiert, fotografierte, hat fotografiert",
    "unterscheiden, unterscheidet, unterschied, hat unterschieden",
    "-weise",
    "oben",
    "die Mühe",
    "ein bisschen",
    "einerseits",
    "parken, parkt, parkte, hat geparkt (D, A)",
    "lange, lang",
    "die Idee, -n",
    "der Traum, ¨-e",
    "der Kunde, -n",
    "zeigen, zeigt, zeigte, hat gezeigt",
    "der Vorschlag, ¨-e",
    "ausgehen, geht aus, ging aus, ist ausgegangen",
    "der See, -n",
    "erhalten, erhält, erhielt, hat erhalten",
    "der Weg, -e",
    "hallo",
    "die Medien (Pl.)",
    "zahlen, zahlt, zahlte, hat gezahlt",
    "senden, sendet, sendete/sandte, hat gesendet/gesandt",
    "→ D, A: Aufzug",
    "das Diplom, -e",
    "starten, startet, startete, ist gestartet",
    "perfekt",
    "die Kirche, -n",
    "(sich) verändern, verändert, veränderte, hat verändert",
    "die Tablette, -n",
    "die Liste, -n",
    "der Rabatt, -e",
    "der Schlaf",
    "der Inhalt, -e",
    "die Broschüre, -n",
    "sehr",
    "der Friede, Frieden, -",
    "beantragen, beantragt, beantragte, hat beantragt",
    "bekannt geben, gibt bekannt, gab bekannt, hat bekannt gegeben",
    "der Wein, -e",
    "die Handwerkerin, -nen",
    "sich vergnügen, vergnügt sich, vergnügte sich, hat sich vergnügt",
    "die Stewardess, -en",
    "bar",
    "sich nähern, nähert sich, näherte sich, hat sich genähert",
    "klagen, klagt, klagte, hat geklagt",
    "bewegen, bewegt, bewegte, hat bewegt",
    "einfallen, fällt ein, fiel ein, ist eingefallen",
    "erlauben, erlaubt, erlaubte, hat erlaubt",
    "der Schuh, -e",
    "der Magen, ¨-",
    "klappen, klappt, klappte, hat geklappt",
    "kostenlos",
    "der Radfahrer, -",
    "der Ort, -e",
    "dick",
    "→ D: Imbiss; A: Jause",
    "löschen, löscht, löschte, hat gelöscht",
    "die Figur, -en",
    "schmecken, schmeckt, schmeckte, hat geschmeckt",
    "(sich) trennen, trennt, trennte, hat getrennt",
    "die Brille, -n",
    "die Tante, -n",
    "die Schokolade",
    "weiblich",
    "führen, führt, führte, hat geführt",
    "der Anrufbeantworter, -",
    "schminken, schminkt, schminkte, hat geschminkt",
    "das Personal",
    "das Visum, Visa",
    "parkieren, parkiert, parkierte, hat parkiert (CH)",
    "der Fehler, -",
    "die Übernachtung, -en",
    "das Büro, -s",
    "(sich) ausruhen, ruht aus, ruhte aus, hat ausgeruht",
    "ausschließen, schließt aus, schloss aus, hat ausgeschlossen",
    "der Sänger, -",
    "schreiben, schreibt, schrieb, hat geschrieben",
    "das Abonnement, -s/-e",
    "füttern, füttert, fütterte, hat gefüttert",
    "das Loch, ¨-er",
    "sich scheiden lassen, lässt sich scheiden, ließ sich scheiden, hat sich scheiden lassen",
    "die Note, -n",
    "die Schuld",
    "verdienen, verdient, verdiente, hat verdient",
    "die Rente, -n (D, CH)",
    "der Terminkalender, -",
    "das Alter",
    "das Ohr, -en",
    "schließen, schließt, schloss, hat geschlossen",
    "das Streichholz, ¨-er",
    "abheben, hebt ab, hob ab, hat abgehoben",
    "die Vergangenheit",
    "die Firma, Firmen",
    "das Gesicht, -er",
    "nervös",
    "der Himmel",
    "sich freuen, freut sich, freute sich, hat sich gefreut",
    "steil",
    "die Reklame, -n",
    "schießen, schießt, schoss, hat geschossen",
    "die Rose, -n",
    "die Verwaltung, -en",
    "Einzel-",
    "kühl",
    "bei",
    "weg/weg-",
    "die Sonne",
    "die Spritze, -n",
    "mündlich",
    "blond",
    "der Führerausweis, -e (CH)",
    "arbeitslos",
    "Öko- (ökologisch)",
    "der Architekt, -en",
    "rechtzeitig",
    "zusätzlich",
    "der Laden, ¨-",
    "die Freizeit",
    "beschäftigen, beschäftigt, beschäftigte, hat beschäftigt",
    "gießen, gießt, goss, gegossen",
    "die Etage, -n (D, CH)",
    "der Sieg, -e",
    "zunehmen, nimmt zu, nahm zu, hat zugenommen",
    "einpacken, packt ein, packte ein, hat eingepackt",
    "die Praxis",
    "der Käufer, -",
    "der Standpunkt, -e",
    "festnehmen, nimmt fest, nahm fest, hat festgenommen",
    "farbig",
    "jeder, jedes, jede",
    "das Geschlecht, -er",
    "die Unterhaltung, -en",
    "die Hausmeisterin, -nen (D, A)",
    "die Tat, -en",
    "verlieren, verliert, verlor, hat verloren",
    "der Schatten, -",
    "die Entwicklung, -en",
    "vorn, vorne",
    "der Donner, -",
    "der Titel, -",
    "der Ausdruck, -e",
    "schuld",
    "beenden, beendet, beendete, hat beendet",
    "der Kasten, ¨- (A, CH)",
    "der Moment, -e",
    "das Opfer, -",
    "→ D: Brötchen; A: Semmel",
    "unterstützen, unterstützt, unterstützte, hat unterstützt",
    "das/der (Schlag-)Obers (A)",
    "die Hochzeit, -en",
    "die Bürste, -n",
    "der Fall, ¨-e",
    "das Netzwerk, -e",
    "die Statistik, -en",
    "sich etwas gefallen lassen, lässt sich etwas gefallen, ließ sich etwas gefallen, hat sich etwas gefallen lassen",
    "die Tochter, ¨-",
    "die Bremse, -n",
    "die Kasse, -n",
    "der Fauteuil, -s (A, CH)",
    "vorsichtig",
    "die Hauptstadt, ¨-e",
    "die Empfehlung, -en",
    "bezahlen, bezahlt, bezahlte, hat bezahlt",
    "die Rezeption/Reception, -en",
    "stumm",
    "weinen, weint, weinte, hat geweint",
    "die Zeugin, -nen",
    "die Bekannte, -n",
    "die Sekretärin, -nen",
    "→ Tomate",
    "schief",
    "der Kollege, -n",
    "die Neuigkeit, -en",
    "eigen-",
    "erschrecken, erschrickt, erschrak, ist erschrocken/ jdn. erschrecken, erschreckt, erschreckte, hat erschreckt",
    "negativ",
    "wahr",
    "entschuldigen, entschuldigt, entschuldigte, hat entschuldigt",
    "der Vorort, -e",
    "garantieren, garantiert, garantierte, hat garantiert",
    "denn",
    "die Gesundheit",
    "die Regel, -n",
    "die Botschaft, -en",
    "das Risiko, Risiken",
    "die Oma, -s",
    "das Erdgeschoss/ Ergeschoß, -e",
    "abstimmen, stimmt ab, stimmte ab, hat abgestimmt",
    "lassen, lässt, ließ, hat gelassen",
    "das Fieber",
    "die Uhr, -en",
    "der Kopf, ¨-e",
    "zwischen",
    "die Zeichnung, -en",
    "der Lohn, ¨-e",
    "link-",
    "worüber",
    "fühlen, fühlt, fühlte, hat gefühlt",
    "wählen, wählt, wählte, hat gewählt",
    "lachen, lacht, lachte, hat gelacht",
    "der Kursleiter, -",
    "teuer",
    "maximal",
    "hungrig",
    "der Garten, ¨-",
    "kritisieren, kritisiert, kritisierte, hat kritisiert",
    "anwesend",
    "das Orchester, -",
    "die Gefahr, -en",
    "technisch",
    "neu",
    "das Meer, -e",
    "Elektro-",
    "leid tun, tut leid, tat leid, hat leidgetan",
    "die Menge, -n",
    "erzählen, erzählt, erzählte, hat erzählt",
    "zugänglich",
    "das Buch, ¨-er",
    "meinen, meint, meinte, hat gemeint",
    "sich verlieben, verliebt sich, verliebte sich, hat sich verliebt",
    "der Bedarf",
    "die Bahn, -en",
    "die Tomate, -n",
    "die Durchsage, -n",
    "begrüßen, begrüßt, begrüßte, hat begrüßt",
    "lieben, liebt, liebte, hat geliebt",
    "das Viertel, - (D, A)",
    "die Händlerin, -nen",
    "die Schularbeit, -en (A)",
    "voraus",
    "bequem",
    "nützen, nützt, nützte, hat genützt",
    "die Verspätung, -en",
    "die Kultur, -en",
    "die Straße, -n",
    "siegen, siegt, siegte, hat gesiegt",
    "der Bewohner, -",
    "der Händler, -",
    "der Bus, -se",
    "sich befinden, befindet sich, befand sich, hat sich befunden",
    "einführen, führt ein, führte ein, hat eingeführt",
    "der Gast, ¨-e",
    "der Studierende, -n",
    "gratis",
    "das Geld",
    "die Anlage, -n",
    "der Schreck(en)",
    "die Zone, -n",
    "un-",
    "die Integration, -en",
    "empfehlen, empfiehlt, empfahl, hat empfohlen",
    "die Verbindung, -en",
    "informieren, informiert, informierte, hat informiert",
    "das Fest, -e",
    "der Schritt, -e",
    "extra",
    "entspannend",
    "der Wohnsitz, -e",
    "die Planung, -en",
    "Spezial-",
    "verliebt",
    "die Chefin, -nen",
    "drehen, dreht, drehte, hat gedreht",
    "plötzlich",
    "der Führerschein, -e (D, A)",
    "die Raucherin, -nen",
    "der Bancomat/Bankomat, -en (A, CH)",
    "das Video, -s",
    "der Paradeiser, - (A)",
    "der Verbrecher, -",
    "die Qualität, -en",
    "stechen, sticht, stach, hat gestochen",
    "der Hausmeister, -",
    "die Ferien (Pl.) (CH)",
    "frühstücken, frühstückt, frühstückte, hat gefrühstückt",
    "Ratschlag, ¨-e",
    "→ D, A: Eis",
    "notieren",
    "elektronisch",
    "der Beweis, -e",
    "anklicken, klickt an, klickte an, hat angeklickt",
    "der Handel",
    "die Darstellung, -en",
    "der Prozess, -e",
    "das Knie, -",
    "das Abitur (D)",
    "die Versammlung, -en",
    "die Pflegerin, -nen",
    "relativ",
    "das Zündholz, ¨-er",
    "das Suchtmittel, -",
    "die Studierende, -n",
    "sich langweilen, langweilt, langweilte, hat gelangweilt",
    "riesig",
    "die Hausaufgabe, -n",
    "sodass",
    "reiten, reitet, ritt, ist geritten",
    "eilen, eilt, eilte, hat/ist geeilt",
    "die Wahl, -en",
    "unterlassen, unterlässt, unterließ, hat unterlassen",
    "das Pflaster, -",
    "die Verliererin, -nen",
    "Kriminal-",
    "das Schreiben, -",
    "haben, hat, hatte, hat gehabt",
    "→ A, CH: Kasten",
    "der Kloß, ¨-e (D)",
    "der Vorteil, -e",
    "betreuen, betreut, betreute, hat betreut",
    "→ D, A: Viertel",
    "wirklich",
    "anstrengend",
    "die Kindheit",
    "die Erkältung, -en",
    "die Methode, -n",
    "das Problem, -e",
    "hübsch",
    "die Teilnahme, -n",
    "scheinen, scheint, schien, hat geschienen",
    "dorthin",
    "die Religion, -en",
    "geeignet",
    "höflich",
    "die Vorfahrt",
    "worum",
    "→ der Briefumschlag; CH: Couvert",
    "der Ausflug, ¨-e",
    "die Kantine, -n",
    "korrekt",
    "hinter/hinter-",
    "→ A, CH: Fauteuil",
    "die Sorge, -n",
    "der Kampf, ¨-e",
    "die Pensionistin, -nen (A)",
    "das Recht, -e",
    "mehrere",
    "besprechen, bespricht, besprach, hat besprochen",
    "die Betreuung",
    "sich bedanken, bedankt, bedankte, hat bedankt",
    "der Raucher, -",
    "die Mahlzeit, -en",
    "Verzeihung",
    "der Kakao, -s",
    "treu",
    "der Keller, -",
    "der Zivilstand (CH)",
    "der Verlierer, -",
    "der Bart, ¨-e",
    "weil",
    "die Matura (A, CH)",
    "nützlich",
    "ehrlich",
    "anwenden, wendet an, wandte an, hat angewandt/angewendet",
    "die Region, -en",
    "hinweisen, weist hin, wies hin, hat hingewiesen",
    "der Humor",
    "klingeln, klingelt, klingelte, hat geklingelt",
    "selten",
    "trotzdem",
    "der Schein, -e",
    "die Tabelle, -n",
    "wer",
    "sich anstrengen, strengt sich an, strengte sich an, hat sich angestrengt",
    "optimistisch",
    "die Größe, -n",
    "bereit",
    "der Bürger, -",
    "lecker",
    "die Saison, -s",
    "die Pizza, -s/Pizzen",
    "ordnen, ordnet, ordnete, hat geordnet",
    "das Haar, -e",
    "kriegen, kriegt, kriegte, hat gekriegt",
    "das Eck, -en (A)",
    "die Freude",
    "sich entschließen, entschließt sich, entschloss sich, hat sich entschlossen",
    "das Einkommen, -",
    "klar",
    "fließen, fließt, floss, ist geflossen",
    "jung",
    "→ Briefträger",
    "der Ball, ¨-e",
    "messen, misst, maß, hat gemessen",
    "die Kleidung",
    "der Strumpf, ¨-e",
    "das Licht, -er",
    "präsentieren",
    "die Leute (Pl.)",
    "das Rüebli, - (CH)",
    "die Jacke, -n",
    "die Wissenschaftlerin, -nen",
    "(sich) verabschieden, verabschiedet, verabschiedete, hat verabschiedet",
    "→ D, CH: Stuhl",
    "erschöpft",
    "die Ernährung",
    "verschieden",
    "der Korridor, -e (D, CH)",
    "das Forum, Foren (Internetforum)",
    "die Kabine, -n",
    "abbiegen, biegt ab, bog ab, ist abgebogen",
    "→ A: (Schlag-)Obers; CH: (Schlag-)Rahm",
    "→ D, A: Nachspeise",
    "die Unterschrift, -en",
    "die Einzahlung, -en",
    "die Muttersprache, -n",
    "→ D, A: Topf",
    "die Bohne, -n",
    "die Reparatur, -en",
    "→ D, A: in Pension gehen/sein; CH, D: pensioniert werden/sein",
    "die Kundin, -nen",
    "gründlich",
    "übermorgen",
    "die Überzeugung, -en",
    "glatt",
    "der Fluss, ¨-e",
    "die Ahnung",
    "endgültig",
    "das Herz, -en",
    "kaputt",
    "unterschreiben, unterschreibt, unterschrieb, hat unterschrieben",
    "das Gebäude, -",
    "die Fachfrau, -en",
    "die Zitrone, -n",
    "loben, lobt, lobte, hat gelobt",
    "mitteilen, teilt mit, teilte mit, hat mitgeteilt",
    "laufen, läuft, lief, ist gelaufen",
    "der Einbruch, ¨-e",
    "der Stress",
    "das Schmerzmittel, -",
    "absolut",
    "sich irren, irrt sich, irrte sich, hat sich geirrt",
    "die Entscheidung, -en",
    "→ CH: Billet",
    "die Pause, -n",
    "entstehen, entsteht, entstand, ist entstanden",
    "der Bericht, -e",
    "die Fremdsprache, -n",
    "besonders",
    "der Kühlschrank, ¨-e",
    "der Pfleger, -",
    "dagegen",
    "→ Personenstand; CH: Zivilstand",
    "die Verkäuferin, -nen",
    "(sich) vorstellen, stellt vor, stellte vor, hat vorgestellt",
    "das Schild, -er",
    "der Herr, -en",
    "weit",
    "der Journalist, -en",
    "der Zoll, ¨-e",
    "die Köchin, -nen",
    "operieren, operiert, operierte, hat operiert",
    "das Detail, -s",
    "die Wirklichkeit",
    "der Verkehr",
    "gleichberechtigt",
    "das Alphabet, -e",
    "aufpassen, passt auf, passte auf, hat aufgepasst",
    "hupen, hupt, hupte, hat gehupt",
    "das Konto, Konten",
    "das Flugzeug, -e",
    "die Notiz, -en",
    "der Beginn",
    "der Familienname, -n",
    "wohl",
    "wieder/wieder-",
    "bloß",
    "das Reisebüro, -s",
    "der Protest, -e",
    "geschehen, geschieht, geschah, ist geschehen",
    "der Dialekt, -e",
    "der Salat, -e",
    "das Gas",
    "probieren, probiert, probierte, hat probiert (D, CH)",
    "zumachen, macht zu, machte zu, hat zugemacht",
    "der Wettbewerb, -e",
    "bestrafen, bestraft, bestrafte, hat bestraft",
    "das Ticket, -s",
    "der Eintritt",
    "sich beteiligen, beteiligt sich, beteiligte sich, hat sich beteiligt",
    "der Urlaub, -e (D, A)",
    "die Aufforderung, -en",
    "der Perron, -s (CH)",
    "der Geburtstag, -e",
    "furchtbar",
    "abwesend",
    "die Kunst, ¨-e",
    "fliegen, fliegt, flog, ist geflogen",
    "die Reise, -n",
    "der Zweck, -e",
    "beschließen, beschließt, beschloss, hat beschlossen",
    "die Bevölkerung",
    "achten, achtet, achtete, hat geachtet (auf)",
    "höchstens",
    "die Heldin, -nen",
    "wunderbar",
    "das Klima",
    "die Urkunde, -n",
    "das Kind, -er",
    "der Nichtraucher, -",
    "voneinander",
    "schneien, es schneit, es schneite, es hat geschneit",
    "überhaupt",
    "der Dreck",
    "winken, winkt, winkte, hat gewinkt",
    "der Ausgang, ¨-e",
    "die Müllabfuhr",
    "das Leder",
    "für",
    "das Trottoir, -s (CH)",
    "soviel",
    "etwa",
    "der Reporter, -",
    "klasse",
    "die Pfanne, -n (CH)",
    "die Forderung, -en",
    "die Bank, ¨-e",
    "die Besserung",
    "gelten, gilt, galt, hat gegolten",
    "die Dauer",
    "die Zünder (A) (Pl.)",
    "vorhin",
    "die Lehre",
    "die Meldung, -en",
    "verlassen, verlässt, verließ, hat verlassen",
    "die Ruhe",
    "sich erkälten, erkältet sich, erkältete sich, hat sich erkältet",
    "verbringen, verbringt, verbrachte, hat verbracht",
    "das Heft, -e",
    "die Ausländerin, -nen",
    "begrenzt",
    "inklusive",
    "das Wasser",
    "der Fotoapparat, -e",
    "die Konkurrenz",
    "toll",
    "gewöhnen, gewöhnt, gewöhnte, hat gewöhnt/ist gewöhnt",
    "die Richterin, -nen",
    "die Landwirtschaft",
    "die Kriminalpolizei",
    "→ CH: Quartier",
    "der Pilz, -e",
    "vegetarisch",
    "die Steckdose, -n",
    "der Anzug, ¨-e",
    "dekorieren, dekoriert, dekorierte, hat dekoriert",
    "bunt",
    "bisher",
    "das Fahrrad, ¨-er",
    "bekannt",
    "wertlos",
    "die Geschwindigkeitsbeschränkung, -en",
    "locker",
    "der Knödel, - (D, A)",
    "welcher, welche, welches",
    "geschieden",
    "telefonieren, telefoniert, telefonierte, hat telefoniert",
    "wertvoll",
    "handeln, handelt, handelte, hat gehandelt",
    "schieben, schiebt, schob, hat geschoben",
    "wegen",
    "der Dialog, -e",
    "also",
    "pünktlich",
    "die Fahrbahn, -en",
    "das Institut, -e",
    "extrem",
    "→ D, CH: Rente",
    "das Erlebnis, -se",
    "der Zahn, ¨-e",
    "die Wiese, -n",
    "lügen, lügt, log, hat gelogen",
    "die Erholung, -en",
    "untersagt",
    "die Speisekarte, -n",
    "erfüllen, erfüllt, erfüllte, hat erfüllt",
    "Speise-/-speise, -n",
    "die Intelligenz",
    "die Wiederholung, -en",
    "die Leiterin, -nen",
    "das Hobby, -s",
    "begeistert",
    "das Kuvert, -s (A)",
    "die Gewerkschaft, -en",
    "→ Praxis",
    "die Enttäuschung, -en",
    "→ Gang; D, CH: Korridor",
    "das Altersheim, -e",
    "der Rechner, -",
    "der Lerner, -",
    "die Heizung, -en",
    "der Personenstand",
    "der Nagel, ¨-",
    "die Behörde, -n",
    "die Form, -en",
    "die Klingel, -n",
    "der Supermarkt, ¨-e",
    "auftreten, tritt auf, trat auf, ist aufgetreten",
    "das Holz",
    "die Aushilfe, -n",
    "die Brust",
    "schließlich",
    "neben",
    "der Ausweis, -e",
    "vorläufig",
    "(hinunter) runterwerfen, wirft runter, warf runter, hat runtergeworfen",
    "danke",
    "reagieren, reagiert, reagierte, hat reagiert",
    "sich einigen, einigt sich, einigte sich, hat sich geeinigt",
    "enden, endet, endete, hat geendet",
    "das Müesli/Müsli, -",
    "der Rentner, -",
    "nehmen, nimmt, nahm, hat genommen",
    "der Herd, -e",
    "die Visitenkarte, -n",
    "das Hallenbad, ¨-er",
    "installieren, installiert, installierte, hat installiert",
    "vermeiden, vermeidet, vermied, hat vermieden",
    "einzeln",
    "die Zange, -n",
    "der Vorort, -e",
    "integrieren, integriert, integrierte, hat integriert",
    "die Enkelin, -nen",
    "→ D, A: Friseur",
    "das Gebäck",
    "das Dokument, -e",
    "auffallen, fällt auf, fiel auf, ist aufgefallen",
    "der Übersetzer, -",
    "die Diskussion, -en",
    "absagen, sagt ab, sagte ab, hat abgesagt",
    "die Mensa, -s/-en",
    "die Beziehung, -en",
    "teilen, teilt, teilte, hat geteilt",
    "warum",
    "behindern, behindert, behinderte, hat behindert behindert",
    "die Höhe",
    "Bescheid geben",
    "das Symbol, -e",
    "erwachsen",
    "der Zettel, -",
    "mögen, mag, mochte, hat gemocht",
    "hinten",
    "der Gegner, -",
    "das Werkzeug, -e",
    "der Zuhörer",
    "der Abschnitt, -e",
    "die Betreuerin, -nen",
    "die Ankunft",
    "die Seite, -n",
    "die Industrie, -n",
    "die Hose, -n",
    "das Inserat, -e",
    "während",
    "sich amüsieren, amüsiert sich, amüsierte sich, hat sich amüsiert",
    "leise",
    "praktisch",
    "sich eignen, eignet sich, eignete sich, hat sich geeignet",
    "die Fahrkarte, -n",
    "das Gehalt, ¨-er",
    "der Roman, -e",
    "berechnen, berechnet, berechnete, hat berechnet",
    "die Überschrift, -en",
    "böse",
    "das Urteil, -e",
    "ab",
    "die Überweisung, - en",
    "der Kreis, -e",
    "fressen, frisst, fraß, hat gefressen",
    "das Rätsel, -",
    "die Teilzeit",
    "das Einschreiben, -",
    "kontrollieren, kontrolliert, kontrollierte, hat kontrolliert",
    "entschlossen",
    "sauber",
    "das Taschengeld, -er",
    "der Bereich, -e",
    "die Badewanne, -n",
    "(sich) verletzen, verletzt, verletzte, hat verletzt",
    "rund",
    "wieso",
    "falsch",
    "gebrauchen, gebraucht, gebrauchte, hat gebraucht",
    "wetten, wettet, wettete, hat gewettet",
    "die Marke, -n",
    "begründen, begründet, begründete, hat begründet",
    "frisch",
    "von",
    "(sich) schneiden, schneidet, schnitt, hat geschnitten",
    "wunderschön",
    "die Aufnahme, -n",
    "die Polizei",
    "→ Dessert",
    "→ D: Hähnchen/Hühnchen; A: Hend(e)l",
    "der Ersatz",
    "vermuten, vermutet, vermutete, hat vermutet",
    "vergessen, vergisst, vergaß, hat vergessen",
    "schlagen, schlägt, schlug, hat geschlagen",
    "heißen, heißt, hieß, hat geheißen",
    "rauf/rauf-",
    "einstellen, stellt ein, stellte ein, hat eingestellt",
    "ausschließlich",
    "die Leiter, -n",
    "erledigen, erledigt, erledigte, hat erledigt",
    "der Notfall, ¨-e",
    "die Erde",
    "die Überstunde, -n",
    "kosten, kostet, kostete, hat gekostet",
    "nochmals",
    "die Decke, -n",
    "das Tal, ¨-er",
    "→ Karotte; CH: Rüebli",
    "überlegen, überlegt, überlegte, hat überlegt",
    "die Anleitung, -en",
    "→ Gehsteig (D, A)",
    "bitte",
    "verteilen, verteilt, verteilte, hat verteilt",
    "besonder-",
    "die Sucht, ¨-e",
    "giftig",
    "zufällig",
    "die Karriere, -n",
    "die Zweitsprache, -n",
    "eng",
    "die Wirtschaft",
    "→ D, A: Fasching; D: Karneval",
    "der Artikel, -",
    "schön",
    "enthalten, enthält, enthielt, hat enthalten",
    "verschreiben, verschreibt, verschrieb, hat verschrieben",
    "die Bedingung, -en",
    "sitzen, sitzt, saß, hat/ist gesessen",
    "die Qualifikation, -en",
    "berühmt",
    "der Musiker, -",
    "(sich) verstecken, versteckt, versteckte, hat versteckt",
    "der Berg, -e",
    "die Mode, -n",
    "niemand",
    "der Basketball, ¨-e",
    "der Fasching, - (D, A)",
    "die Ware, -n",
    "die Wettervorhersage, -n",
    "gering",
    "der Coiffeur, -e",
    "das Gift, -e",
    "die Beschäftigung",
    "schrecklich",
    "folgen, folgt, folgte, ist gefolgt",
    "die Journalistin, -nen",
    "die Ecke, -n (D, CH)",
    "die Sängerin, -nen",
    "geschieden",
    "spätestens",
    "danach",
    "die Limonade, -n",
    "die Schulden (Pl.)",
    "der Tisch, -e",
    "die Pflaume, -n",
    "das Stockwerk, -e",
    "verraten, verrät, verriet, hat verraten",
    "das Wissen",
    "die Stiege, -n (A)",
    "gemeinsam",
    "die Party, -s",
    "der Zuhörer, -",
    "→ CH: parkieren",
    "andererseits",
    "verkaufen, verkauft, verkaufte, hat verkauft",
    "die Straßenbahn, -en (D, A)",
    "dass",
    "stören, stört, störte, hat gestört",
    "verbinden, verbindet, verband, hat verbunden",
    "treiben, treibt, trieb, hat getrieben",
    "das Thema, Themen",
    "die Vermietung, -en",
    "elektrisch",
    "ändern, ändert, änderte, hat geändert",
    "auseinander",
    "der Kontakt, -e",
    "der Salon, -s",
    "die Mieterin, -nen",
    "allein",
    "draußen",
    "so",
    "die Kanne, -n",
    "die Suppe, -n",
    "das Amt, ¨-er",
    "das Rad, ¨-er",
    "der Schnee",
    "benutzen, benutzt, benutzte, hat benutzt",
    "werfen, wirft, warf, hat geworfen",
    "vorher",
    "bitten, bittet, bat, hat gebeten",
    "im Freien",
    "komisch",
    "neulich",
    "sich bewerben, bewirbt sich, bewarb sich, hat sich beworben",
    "das Auto, -s",
    "die Biologie",
    "je … desto …",
    "streng",
    "leben, lebt, lebte, hat gelebt",
    "ängstlich",
    "woher",
    "die Frucht, ¨-e",
    "das Kabel, -",
    "der Schutz",
    "beid-",
    "lernen, lernt, lernte, hat gelernt",
    "der Absender, -",
    "gehen, geht, ging, ist gegangen",
    "die Kranke, -n",
    "→ CH: Perron",
    "die Eltern (Pl.)",
    "das Eis",
    "verhaften, verhaftet, verhaftete, hat verhaftet",
    "frieren, friert, fror, hat gefroren",
    "das Märchen, -",
    "seitdem",
    "vertrauen, vertraut, vertraute, hat vertraut",
    "schlecht",
    "der Kompromiss, -e",
    "die Pflanze, -n",
    "die Wand, ¨-e",
    "helfen, hilft, half, hat geholfen",
    "der Streik, -s",
    "die Fortbildung, -en",
    "niedrig",
    "kochen, kocht, kochte, hat gekocht",
    "noch",
    "warm",
    "faulenzen, faulenzt, faulenzte, hat gefaulenzt",
    "die Wolke, -n",
    "zurechtkommen, kommt zurecht, kam zurecht, ist zurechtgekommen",
    "buchen, bucht, buchte, hat gebucht",
    "donnern, donnert, donnerte, hat gedonnert",
    "ausdrucken, druckt aus, druckte aus, hat ausgedruckt",
    "müde",
    "die Kraft, ¨-e",
    "ähnlich",
    "der Partner, -",
    "das Konzert, -e",
    "der Vertreter, -",
    "(ein) paar",
    "illegal",
    "das Kleid, -er",
    "die Wohnung, -en",
    "aber",
    "der Hersteller, -",
    "die Eröffnung, -en",
    "Doppel-",
    "eigentlich",
    "das Zeug/-zeug",
    "die Diät",
    "die Rufnummer, -n",
    "schon",
    "der/das (Schlag-)Obers (A)",
    "das Trinkgeld, -er",
    "der Staub",
    "nutzen, nutzt, nutzte, hat genutzt",
    "fahren, fährt, fuhr, ist/hat gefahren",
    "die Voraussetzung, -en",
    "wehtun, tut weh, tat weh, hat wehgetan",
    "historisch",
    "verantwortlich",
    "staubsaugen, staubsaugt, staubsaugte, hat gestaubsaugt",
    "hinterher",
    "→ D, A: Ober; CH: Serviceangestellter",
    "aufheben, hebt auf, hob auf, hat aufgehoben",
    "vermieten, vermietet, vermietete, hat vermietet",
    "gut",
    "körperlich",
    "das Angebot, -e",
    "interkulturell",
    "genießen, genießt, genoss, hat genossen",
    "unter-",
    "der Sport",
    "die Jeans (Pl.)",
    "gemütlich",
    "(sich) überzeugen, überzeugt, überzeugte, hat überzeugt",
    "entfernen, entfernt, entfernte, hat entfernt",
    "das Quiz",
    "das Gasthaus, ¨-er (A)",
    "die Tradition, -en",
    "was",
    "das Gras",
    "innen",
    "spülen, spült, spülte, hat gespült",
    "das Rezept, -e",
    "feucht",
    "der Mechaniker, -",
    "korrigieren, korrigiert, korrigierte, hat korrigiert",
    "schwierig",
    "→ D: (Schlag-)Sahne; CH: (Schlag-)Rahm",
    "recht-",
    "verpassen, verpasst, verpasste, hat verpasst",
    "der Knochen, -",
    "obwohl",
    "regelmäßig",
    "kämpfen, kämpft, kämpfte, hat gekämpft",
    "zeichnen, zeichnet, zeichnete, hat gezeichnet",
    "brennen, brennt, brannte, hat gebrannt",
    "der Lehrer, -",
    "fallen, fällt, fiel, ist gefallen",
    "kritisch",
    "die Luft",
    "versichern, versichert, versicherte, hat versichert",
    "das Fleisch",
    "gültig",
    "der Zirkus, -se",
    "die Erfindung, -en",
    "die Abbildung, -en",
    "der Stern, -e",
    "das Gegenteil, -e",
    "der Koffer, -",
    "aufgeben, gibt auf, gab auf, hat aufgegeben",
    "die Erlaubnis",
    "der Apfel, ¨-",
    "entdecken, entdeckt, entdeckte, hat entdeckt",
    "verursachen, verursacht, verursachte, hat verursacht",
    "→ D: in Rente gehen/sein; D, CH: pensioniert werden/sein",
    "überprüfen, überprüft, überprüfte, hat überprüft",
    "klären, klärt, klärte, hat geklärt",
    "weiter/weiter-",
    "die Käuferin, -nen",
    "vorgestern",
    "die Ehefrau, -en/der Ehemann, ¨-er",
    "peinlich",
    "beruhigen, beruhigt, beruhigte, hat beruhigt",
    "zuhören, hört zu, hörte zu, hat zugehört",
    "der Abwart, -e",
    "hassen, hasst, hasste, hat gehasst",
    "der Punkt, -e",
    "automatisch",
    "das Rathaus, ¨-er",
    "pensioniert werden/sein (D, CH)",
    "heimlich",
    "das Seminar, -e",
    "treten, tritt, trat, hat/ist getreten",
    "stilistisch",
    "→ CH:dieBriefträgerin,-nen Pöstler",
    "das Geschenk, -e",
    "die Freundschaft, -en",
    "noch mal",
    "die Nichtraucherin, -nen",
    "der Bauch, ¨-e",
    "abgeben, gibt ab, gab ab, hat abgegeben",
    "ablehnen, lehnt ab, lehnte ab, hat abgelehnt",
    "das Verhältnis, -se",
    "die Schriftstellerin, -nen",
    "überraschen, überrascht, überraschte, hat überrascht",
    "→ A: Bankomat-Karte",
    "vorwärts",
    "prima",
    "malen, malt, malte, hat gemalt",
    "ebenfalls",
    "der Motor, -en",
    "der Anfang, ¨-e",
    "das Dessert, -s",
    "der Kanal, ¨-e",
    "bevor",
    "sauer",
    "die Kälte",
    "städtisch",
    "das Getränk, -e",
    "anfangen, fängt an, fing an, hat angefangen",
    "der Fotograf, -en",
    "das Radio, -s",
    "verwenden, verwendet, verwendete, hat verwendet",
    "der Gewinn, -e",
    "suchen, sucht, suchte, hat gesucht",
    "die Nachhilfe, -n",
    "(sich) anziehen, zieht an, zog an, hat angezogen",
    "die Fantasie/Phantasie, -n",
    "vorder-",
    "egal",
    "danken, dankt, dankte, hat gedankt",
    "schimpfen, schimpft, schimpfte, hat geschimpft",
    "das Essen, -",
    "die Tropfen (Pl.)",
    "der Vater, ¨-",
    "sichern, sichert, sicherte, hat gesichert",
    "begleiten, begleitet, begleitete, hat begleitet",
    "die Literatur",
    "die Soße/Sauce, -n",
    "die Umfrage, -n",
    "vorlesen, liest vor, las vor, hat vorgelesen",
    "abwaschen, wäscht ab, wusch ab, hat abgewaschen",
    "der Auftritt, -e",
    "der Onkel, -",
    "der Knopf, ¨-e",
    "→ A: Schwammerl",
    "der Name, -n",
    "der Fuß, ¨-e",
    "die Trennung, -en",
    "der Konflikt, -e",
    "spielen, spielt, spielte, hat gespielt",
    "umsteigen, steigt um, stieg um, ist umgestiegen",
    "der Spielplatz, ¨-e",
    "das Plakat, -e",
    "das Dorf, ¨-er",
    "das Asyl",
    "putzen, putzt, putzte, hat geputzt",
    "die Zahnbürste, -n",
    "der Bahnsteig, -e (D, A)",
    "folgend",
    "die Bewegung, -en",
    "strafbar",
    "das Parfüm, -s",
    "→ A, CH: Matura",
    "einsteigen, steigt ein, stieg ein, ist eingestiegen",
    "die Küste, -n",
    "die Seife, -n",
    "die Lehrstelle, -n",
    "möbliert",
    "die Angst, “-e",
    "das Geschirr",
    "dunkel",
    "die Buchhandlung, -en",
    "die Dusche, -n",
    "berichten, berichtet, berichtete, hat berichtet",
    "die Unterkunft, ¨-e",
    "links",
    "das Netz, -e",
    "steigen, steigt, stieg, ist gestiegen",
    "→ A: Eck",
    "der Klick, - s",
    "die Vollzeit",
    "die Personalien (Pl.)",
    "beeinflussen, beeinflusst, beeinflusste, hat beeinflusst",
    "der Kauf",
    "bestätigen, bestätigt, bestätigte, hat bestätigt",
    "das Theater, -",
    "passieren, passiert, passierte, ist passiert",
    "die Lieferung, -en",
    "der Saft, ¨-e",
    "→ ec-Karte/EC-Karte",
    "die Vertreterin, -nen",
    "hart",
    "der Star, -s",
    "notwendig",
    "die Puppe, -n",
    "die Gemeinschaft, -en",
    "übertreiben, übertreibt, übertrieb, hat übertrieben",
    "die Sprechstunde, -n",
    "der Vorwurf, ¨-e",
    "die Unterlagen (Pl.)",
    "beißen, beißt, biss, hat gebissen",
    "bemerken, bemerkt, bemerkte, hat bemerkt",
    "die Vorschrift, -en",
    "die Taste, -n",
    "die Öffentlichkeit",
    "der Aufenthalt, -e",
    "die Ordination, -en (A)",
    "die Schule, -n",
    "der Gang, ¨-e",
    "der Intensivkurs, -e",
    "einfügen, fügt ein, fügte ein, hat eingefügt",
    "der Halt",
    "behaupten, behauptet, behauptete, hat behauptet",
    "packen, packt, packte, hat gepackt",
    "das Vitamin, -e",
    "wahnsinnig",
    "streiken, streikt, streikte, hat gestreikt",
    "die Frisur, -en",
    "der Tanz, ¨-e",
    "unentschieden",
    "die Kündigung, -en",
    "das Bargeld",
    "die Tasche, -n",
    "möglich",
    "man",
    "mindestens",
    "gewöhnlich",
    "der Briefkasten, ¨-",
    "der Vortrag, ¨-e",
    "die Technologie, -n",
    "die Förderung, -en",
    "wohin",
    "die Reporterin, -nen",
    "aufhören, hört auf, hörte auf, hat aufgehört",
    "das Verständnis",
    "der Autor, -en",
    "der Rücken, -",
    "nachdem",
    "der Hafen, ¨-",
    "der Zugang, ¨-e",
    "doppelt",
    "der Schmerz, -en",
    "die Vorwahl, -en",
    "die Kenntnisse (Pl.)",
    "ruhig",
    "die Ausbildung, -en",
    "die Mehrheit, -en",
    "→ A: Jause, CH: Znüni/Zvieri",
    "das Tram, -s",
    "das Hackfleisch (D, CH)",
    "trotz",
    "die Fotografie, -n",
    "dumm",
    "eher",
    "das Feuer",
    "die Vermieterin, -nen",
    "die Veranstaltung, -en",
    "der Treffpunkt, -e",
    "verpacken, verpackt, verpackte, hat verpackt",
    "der Lift, -e",
    "intelligent",
    "echt",
    "der Rekord, -e",
    "der Mieter, -",
    "herunter-, runter- (herunter-)laden, lädt herunter, lud herunter, hat heruntergeladen",
    "schmutzig",
    "jederzeit",
    "die Generation, -en",
    "nachschlagen, schlägt nach, schlug nach, hat nachgeschlagen",
    "still",
    "die Unternehmerin, -nen",
    "die Tasse, -n",
    "die Herausforderung, -en",
    "die Strecke, -n",
    "das Heimweh",
    "spannend",
    "der Friseur, -e",
    "das Programm, -e",
    "der Stau, -s",
    "→ D, CH: Hackfleisch",
    "die Socke, -n",
    "ledig",
    "behandeln, behandelt, behandelte, hat behandelt",
    "an",
    "endlich",
    "die Laune, -n",
    "jetzt",
    "die Mahnung, -en",
    "wenigstens",
    "regeln, regelt, regelte, hat geregelt",
    "traurig",
    "das Unglück, -e",
    "→ D, CH: Treppe",
    "offiziell",
    "→ D, CH: Etage",
    "die Cafeteria, -s",
    "die Zeile, -n",
    "probieren, probiert, probierte, hat probiert",
    "die Pommes frites (Pl.)",
    "sprechen, spricht, sprach, hat gesprochen",
    "das Messer, -",
    "die Mannschaft, -en",
    "der Kurs, -e",
    "der Ozean, -e",
    "nirgends",
    "die Abfahrt, -en",
    "Tee ziehen lassen",
    "→ D: Junge",
    "die Aprikose, -n (D, CH)",
    "die Partnerin, -nen",
    "verpflichtet",
    "beschädigen, beschädigt, beschädigte, hat beschädigt",
    "die Situation, -en",
    "sowohl … als auch",
    "die Fabrik, -en",
    "da",
    "→ A: (Back-)Rohr",
    "der Feiertag, -e",
    "(sich) siezen, siezt, siezte, hat gesiezt",
    "wollen, will, wollte, hat gewollt (hat wollen als Modalverb)",
    "der Fleck, -en",
    "der Termin, -e",
    "die Burg, -en",
    "die Autorin, -nen",
    "wenig/wenige",
    "das Schiff, -e",
    "mobil/mobil-",
    "→ D: Geldautomat",
    "durchschnittlich",
    "das Couvert, -s (CH)",
    "ohne",
    "die Mappe, -n",
    "finden, findet, fand, hat gefunden",
    "fest",
    "klug",
    "bauen, baut, baute, hat gebaut",
    "der Atem",
    "die Fußgängerzone, -n",
    "die Ausgabe, -n",
    "der Betreuer, -",
    "vermutlich",
    "das (Back-)Rohr, -e (A)",
    "die Kneipe, -n (D)",
    "verbieten, verbietet, verbot, hat verboten",
    "ausgezeichnet",
    "der König, -e",
    "der Bahnhof, ¨-e",
    "der Ingenieur, -e",
    "es",
    "dies-",
    "braten, brät, briet, hat gebraten",
    "das Lokal, -e",
    "der Ärger",
    "→ Kellner; CH: Serviceangestellter",
    "die Kiste, -n (A, D)",
    "wach",
    "die Gaststätte, -n (D)",
    "die Bar, -s",
    "→ D, A: Familienstand; CH: Zivilstand",
    "das Zertifikat, -e",
    "das Hähnchen/Hühnchen, - (D)",
    "die Schwester, -n",
    "→ Lift",
    "übernachten, übernachtet, übernachtete, hat übernachtet",
    "die Geschwister (Pl.)",
    "fantastisch",
    "längst",
    "die Kontrolle, -n",
    "übrigens",
    "gehören, gehört, gehörte, hat gehört",
    "(sich) verstehen, versteht, verstand, hat verstanden",
    "auf",
    "die Ordnung",
    "die Therapie, -n",
    "→ D, CH: Ecke",
    "→ A: Schularbeit",
    "das Stadion, Stadien",
    "das Möbel, -",
    "vorschlagen, schlägt vor, schlug vor, hat vorgeschlagen",
    "die Galerie, -n",
    "sparen, spart, sparte, hat gespart",
    "der Reis",
    "die Mauer, -n",
    "treffen, trifft, traf, hat getroffen",
    "wiegen, wiegt, wog, hat gewogen",
    "kulturell",
    "die Rentnerin, -nen (D, CH)",
    "vor allem",
    "jedoch",
    "das Lied, -er",
    "der Wissenschaftler, -",
    "der Ring, -e",
    "das Medikament, -e",
    "parallel",
    "anhaben, hat an, hatte an, hat angehabt",
    "jemand",
    "die Pension, -en",
    "nebenan",
    "die Fähigkeit, -en",
    "der Doktor, -en",
    "die Siegerin, -nen",
    "verpflegen, verpflegt, verpflegte, hat verpflegt",
    "heben, hebt, hob, hat gehoben",
    "unbedingt",
    "reisen, reist, reiste, ist gereist",
    "der Einfall, ¨-e",
    "das Interview, -s",
    "lösen, löst, löste, hat gelöst",
    "das Abenteuer, -",
    "inner-",
    "→ A: Marille",
    "die Sache, -n",
    "das Gebiet, -e",
    "weltweit",
    "persönlich",
    "der Politiker, -",
    "die Ordination, -en (A)",
    "durch",
    "wann",
    "falls",
    "zusagen, sagt zu, sagte zu, hat zugesagt",
    "küssen, küsst, küsste, hat geküsst",
    "miss-",
    "die Folge, -n",
    "die Musikerin, nen",
    "die Metropole, -n",
    "herzlich",
    "der Boden, ¨-",
    "der Sessel, - (D, CH)",
    "die Maschine, -n",
    "trinken, trinkt, trank, hat getrunken",
    "der Rat",
    "grillen, grillt, grillte, hat gegrillt (D, A)",
    "frech",
    "vorhaben, hat vor, hatte vor, hat vorgehabt",
    "der Geldautomat, -en (D)",
    "sollen, soll, sollte, hat gesollt (hat sollen als Modalverb)",
    "der Erfolg, -e",
    "sich erholen, erholt sich, erholte sich, hat sich erholt",
    "der Handwerker, -",
    "der Saal, Säle",
    "das Fach, ¨-er",
    "der Flug, ¨-e",
    "riechen, riecht, roch, hat gerochen",
    "abwärts",
    "die Klassenarbeit, -en (D)",
    "die Fachleute (Pl.)",
    "individuell",
    "innerhalb",
    "die Kamera, -s",
    "dann",
    "prüfen, prüft, prüfte, hat geprüft",
    "die ec-Karte/EC-Karte",
    "der Schalter, -",
    "→ Pilz schwanger",
    "der Preis, -e",
    "der Praktikant, -en",
    "das Feuerzeug, -e",
    "die Praxis, Praxen",
    "die Bühne, -n",
    "der Tourist, -en",
    "schützen, schützt, schützte, hat geschützt",
    "der Betrag, ¨-e",
    "die Wahrheit, -en",
    "die Abteilung, -en",
    "der Zusammenhang, ¨-e",
    "wie",
    "der Vergleich, -e",
    "die Klimaanlage, -n",
    "holen, holt, holte, hat geholt",
    "quer",
    "öffentlich",
    "arbeiten, arbeitet, arbeitete, hat gearbeitet",
    "→ Briefumschlag; A: Kuvert",
    "die Polizistin, -nen",
    "das Mobiltelefon, -e",
    "antworten, antwortet, antwortete, hat geantwortet",
    "die Wurst, ¨-e",
    "der Balkon, -e",
    "zweifeln, zweifelt, zweifelte, hat gezweifelt",
    "die Umgebung, -en",
    "das Menü, -s",
    "die Touristin, -nen",
    "das Bett, -en",
    "hell",
    "erforderlich",
    "die Möhre, -n (D)",
    "der Kredit, -e",
    "husten, hustet, hustete, hat gehustet",
    "das Gebirge",
    "der Familienstand (D, A)",
    "merkwürdig",
    "→ Zündholz; A: Zünder",
    "tödlich",
    "billig",
    "das Kino, -s",
    "die Krankheit, -en",
    "das Café, -s",
    "das Waschmittel, -",
    "die Gegend, -en",
    "die Flöte, -n",
    "die Art, -en",
    "erwarten, erwartet, erwartete, hat erwartet",
    "die Aufgabe, -n",
]

words_to_create = [Btwo(deu=word) for word in german_words]

Btwo.objects.bulk_create(words_to_create)
